function replot_l6_ei_all_residuals()
% Replot Figure 6.1.2 using every finite HC value regardless of residual.

codeRoot = fileparts(mfilename('fullpath'));
analysisRoot = fileparts(codeRoot);
outputRoot = fullfile( ...
    '/Users/xialeihuang/Desktop/Neuroscience_Project/Spectral_Analysis', ...
    'matlab-inserting_into_CG_model/Complete_Code_for_Paper3', ...
    'NYU-Vision-2Drive-main/Figures/spectral_analysis_eigenvalue_eigenvectors', ...
    'L6 and Inhibition/L6_and_EI_Inhibition_offset');
reportRoot = '/Users/xialeihuang/Desktop/Neuroscience_Project/Spectral_Analysis_Report';
setupFile = fullfile(analysisRoot,'results_global_bifurcation_20260722', ...
    'global_bifurcation_setup.mat');
stem = ['6.1.2_FullGrid_Beta6_BetaEI_Canonical_HCnorm_' ...
    'Heatmap_with_HCnorm3_Boundary'];
referenceClim = [0.391523346338067 36.6263881897836];
unacceptedHCThreshold = 170;

grid = readtable(fullfile(outputRoot,'all_beta6_betaEI_grid_points.tsv'), ...
    'FileType','text','Delimiter','\t','TextType','string');
beta6Values = unique(grid.beta6,'sorted')';
betaEIValues = unique(grid.betaEI,'sorted')';
expectedCount = numel(beta6Values)*numel(betaEIValues);
if height(grid)~=expectedCount || numel(unique(grid.taskId))~=expectedCount
    error('L6EI:Incomplete','Expected %d unique points, found %d.', ...
        expectedCount,height(grid));
end

hcMatrix = nan(numel(betaEIValues),numel(beta6Values));
residualMatrix = nan(size(hcMatrix));
strictMatrix = false(size(hcMatrix));
for row = 1:height(grid)
    i6 = grid.beta6Index(row);
    iEI = grid.betaEIIndex(row);
    hcMatrix(iEI,i6) = grid.HCnorm(row);
    residualMatrix(iEI,i6) = grid.fixedPointResidual(row);
    strictMatrix(iEI,i6) = logical(grid.strictConverged(row));
end
validHC = hcMatrix;
validHC(~isfinite(validHC) | validHC<0) = NaN;
if nnz(isfinite(validHC))~=expectedCount
    error('L6EI:NonfiniteHC','Not all %d grid points have finite HC values.', ...
        expectedCount);
end

[bestBetaEI,bestHC,regressionSlope] = local_best_path( ...
    beta6Values,betaEIValues,validHC);
bestPath = table(beta6Values(:),bestBetaEI(:),bestHC(:), ...
    'VariableNames',{'beta6','betaEI','minimumHCnorm'});
writetable(bestPath,fullfile(outputRoot,'best_compensation_path.tsv'), ...
    'FileType','text','Delimiter','\t');

fpp = readtable(fullfile(outputRoot,'theoretical_fpp_slope_audit.tsv'), ...
    'FileType','text','Delimiter','\t');
fppSlope = fpp.slopeL6ItoE(1);
hcSlopeAudit = readtable(fullfile(outputRoot, ...
    'theoretical_hc_optimal_fixedpoint_slope_audit.tsv'), ...
    'FileType','text','Delimiter','\t');
hcSlope = hcSlopeAudit.slopeL6ItoE(end);

highHCMask = validHC>unacceptedHCThreshold;
metrics = table( ...
    ["grid_condition_count";"finite_HC_condition_count"; ...
    "residual_rejected_condition_count";"strict_converged_condition_count"; ...
    "HCnorm_le_2_count";"HCnorm_le_5_count"; ...
    "HCnorm_gt_170_display_gray_count";"minimum_HCnorm"; ...
    "maximum_HCnorm";"maximum_fixed_point_residual"; ...
    "minimum_HC_regression_betaEI_per_beta6"; ...
    "theoretical_FPP_slope_betaEI_per_beta6"; ...
    "moved_FP_HC_slope_betaEI_per_beta6"], ...
    [expectedCount;nnz(isfinite(validHC));0;nnz(strictMatrix); ...
    nnz(validHC<=2);nnz(validHC<=5);nnz(highHCMask); ...
    min(validHC,[],'all','omitnan');max(validHC,[],'all','omitnan'); ...
    max(residualMatrix,[],'all','omitnan');regressionSlope; ...
    fppSlope;hcSlope],'VariableNames',{'metric','value'});
writetable(metrics,fullfile(outputRoot,'full_grid_metrics.tsv'), ...
    'FileType','text','Delimiter','\t');

fig = local_plot(beta6Values,betaEIValues,validHC,referenceClim, ...
    unacceptedHCThreshold,hcSlope,regressionSlope);
figureRoot = fullfile(outputRoot,'figures');
if ~exist(figureRoot,'dir'); mkdir(figureRoot); end
local_save(fig,outputRoot,stem);
local_save(fig,figureRoot,stem);
copyfile(fullfile(outputRoot,[stem '.pdf']), ...
    fullfile(reportRoot,[stem '.pdf']),'f');
close(fig);

save(fullfile(outputRoot,'all_residuals_plot_results.mat'), ...
    'grid','beta6Values','betaEIValues','hcMatrix','validHC', ...
    'residualMatrix','strictMatrix','bestPath','metrics','fppSlope', ...
    'hcSlope','hcSlopeAudit','regressionSlope','referenceClim', ...
    'unacceptedHCThreshold','-v7.3');
fprintf(['Replotted %d/%d finite-HC points without residual rejection; ' ...
    '%d points above %g Hz shown in gray.\n'],nnz(isfinite(validHC)), ...
    expectedCount,nnz(highHCMask),unacceptedHCThreshold);
end

function [bestY,bestHC,slope] = local_best_path(xValues,yValues,validHC)
bestY = nan(size(xValues));
bestHC = nan(size(xValues));
for xIndex = 1:numel(xValues)
    [bestHC(xIndex),rowIndex] = min(validHC(:,xIndex),[],'omitnan');
    bestY(xIndex) = yValues(rowIndex);
end
fitMask = isfinite(bestY) & isfinite(xValues);
fitX = xValues(fitMask);
fitY = bestY(fitMask);
slope = sum(fitX.*fitY)/sum(fitX.^2);
end

function fig = local_plot(xValues,yValues,validHC,colorLimits, ...
        highHCThreshold,hcSlope,regressionSlope)
fig = figure('Visible','off','Color','w','Position',[80 80 1280 1020]);
highHCMask = validHC>highHCThreshold;
heatHC = validHC;
heatHC(highHCMask) = NaN;
heatmapImage = imagesc(xValues,yValues,heatHC);
heatmapImage.AlphaData = isfinite(heatHC);
ax = gca;
set(ax,'YDir','normal','Color',[0.80 0.80 0.80]);
axis(ax,'xy');
axis(ax,'tight');
hold(ax,'on');

grayValue = 0.45;
grayRGB = repmat(grayValue,[size(validHC) 3]);
grayLayer = imagesc(ax,xValues,yValues,grayRGB);
grayLayer.AlphaData = double(highHCMask);
hHighHC = plot(ax,nan,nan,'s','MarkerSize',9, ...
    'MarkerFaceColor',grayValue*[1 1 1], ...
    'MarkerEdgeColor',grayValue*[1 1 1]);

hHC = local_slope_line(ax,xValues,yValues,hcSlope,'--',[0.75 0 0.75]);
hRegression = local_slope_line(ax,xValues,yValues,regressionSlope, ...
    '-',[0.35 0.35 0.35]);
[~,hBoundary3] = contour(ax,xValues,yValues,validHC,[2 2], ...
    'LineColor','k','LineWidth',1.25);
[~,hBoundary10] = contour(ax,xValues,yValues,validHC,[5 5], ...
    'LineColor',[0.20 0.20 0.20],'LineStyle','--','LineWidth',0.9);

xlabel(ax,'\beta_6 (fractional whole-L6 increase)', ...
    'FontSize',22,'FontWeight','bold');
ylabel(ax,'\beta_{EI} (fractional I-to-E inhibition increase)', ...
    'FontSize',22,'FontWeight','bold');
set(ax,'FontSize',19,'FontWeight','bold','LineWidth',1.25, ...
    'XGrid','off','YGrid','off','ColorScale','log');
colormap(fig,jet(256));
clim(ax,colorLimits);
cb = colorbar(ax);
cb.Ticks = [1 10];
cb.FontSize = 17;
cb.Label.String = 'HC norm';
cb.Label.FontSize = 19;
cb.Label.FontWeight = 'bold';
cb.Title.String = 'Hz';
cb.Title.FontSize = 17;
cb.Title.FontWeight = 'bold';
legend(ax,[hHC hRegression hBoundary3 hBoundary10 hHighHC], ...
    {sprintf('moved-FP HC slope %.6f',hcSlope), ...
    sprintf('minimum-HC regression %.6f',regressionSlope), ...
    'HC norm = 2 Hz','HC norm = 5 Hz', ...
    sprintf('HC norm > %g Hz (unaccepted)',highHCThreshold)}, ...
    'Location','northoutside','Orientation','horizontal', ...
    'NumColumns',3,'FontSize',11.5,'FontWeight','bold', ...
    'Box','off');
end

function handle = local_slope_line(ax,xValues,yValues,slope,style,color)
lineX = linspace(min(xValues),max(xValues),500);
lineY = slope*lineX;
inside = lineY>=min(yValues) & lineY<=max(yValues);
handle = plot(ax,lineX(inside),lineY(inside),style, ...
    'Color',color,'LineWidth',2.2);
end

function local_save(fig,outputRoot,stem)
savefig(fig,fullfile(outputRoot,[stem '.fig']));
exportgraphics(fig,fullfile(outputRoot,[stem '.pdf']), ...
    'ContentType','vector');
end
