function smoke_figure1g_exact_paper3_cg(runRoot)
% Time the untouched Paper 3 CG wrapper after connectivity is constructed.
addpath(fullfile(runRoot,'repo','Utils'),'-begin');
addpath(fullfile(runRoot,'fast'),'-begin');
addpath(fullfile(runRoot,'code'),'-begin');
threads = str2double(getenv('SLURM_CPUS_PER_TASK'));
if isfinite(threads) && threads>=1
    maxNumCompThreads(threads);
end
sourceFile = fullfile(runRoot,'repo','Data','Paper2_NetworkTuning','Fig1V4', ...
    'Paper3PlotingData','Func200V4D2-L6RealCtrlL4-Ang0.0-SF2.5TF10-Small.mat');
D = load(sourceFile,'L4EmeshX','L4ImeshY','LDEFrfunc');
modelFile = fullfile(runRoot,'fast','h96_models_double.mat');
for fieldHC = [4 40]
    B = load(fullfile(runRoot,'bundles',sprintf('field_%02dHC.mat',fieldHC)), ...
        'ctx','initialState');
    ctx = B.ctx;
    timer = tic;
    [states,~,~,~,~,~,nanFlag] = LDEIteration_135FuncMain_CombDom_RealLGNL6( ...
        ctx.PixLGNCtgr,ctx.L6Kernel,B.initialState,ctx.p,ctx.L6pars{ctx.L6parId},50, ...
        ctx.C_SS_meanU,ctx.C_CS_meanU,ctx.C_IS_mean, ...
        ctx.C_SC_meanU,ctx.C_CC_meanU,ctx.C_IC_mean, ...
        ctx.C_SI_mean,ctx.C_CI_mean,ctx.C_II_mean, ...
        ctx.L4SEp,ctx.L4SIp,ctx.L4CEp,ctx.L4CIp,ctx.L4IEp,ctx.L4IIp, ...
        {D.L4EmeshX},{D.L4ImeshY},{D.LDEFrfunc},[1;2;3;4], ...
        ctx.N_HCOutY,ctx.NPixX,ctx.NPixY,true,'xn',ctx.EKpUse,ctx.IKpUse);
    cgSeconds = toc(timer);
    assert(~nanFlag,'Exact Paper 3 CG wrapper returned NaN.');
    finalCG = states{end};

    base = h96_nn_prepare_base(ctx,'single',modelFile);
    fast = h96_nn_set_condition_symmetry(base,100,0);
    [finalDNN,dnnInfo] = h96_nn_fixedpoint_symmetry(B.initialState,fast,50);
    fprintf(['FIELD=%d EXACT_PAPER3_CG50=%.6f OPT_DNN50=%.6f SPEEDUP=%.3f ', ...
        'CG_CHECKSUM=%.12g DNN_CHECKSUM=%.12g\n'],fieldHC,cgSeconds, ...
        dnnInfo.Seconds,cgSeconds/dnnInfo.Seconds, ...
        sum(finalCG.S)+sum(finalCG.C)+sum(finalCG.I), ...
        sum(finalDNN.S)+sum(finalDNN.C)+sum(finalDNN.I));
end
end
