function validate_dnn_thread_probe(sourceRoot,outputRoot,repeatId,nnThreads)
% Time candidate first in a fresh process; reference runs only afterward.
run_dnn_thread_probe(sourceRoot,outputRoot,repeatId,nnThreads,'validation');
run_dnn_thread_probe(sourceRoot,outputRoot,repeatId,16,'reference');
r = str2double(string(repeatId)); t = str2double(string(nnThreads));
candidate = load(fullfile(outputRoot,'validation',sprintf( ...
    'dnn_03HC_threads_%02d_repeat_%03d.mat',t,r)),'state','T');
reference = load(fullfile(outputRoot,'reference',sprintf( ...
    'dnn_03HC_threads_16_repeat_%03d.mat',r)),'state','T');
error = abs([candidate.state.S;candidate.state.C;candidate.state.I] - ...
    [reference.state.S;reference.state.C;reference.state.I]);
maxAbs = max(error); meanAbs = mean(error);
sameIterations = candidate.T.Iterations==reference.T.Iterations;
residualDifference = abs(candidate.T.FinalResidual-reference.T.FinalResidual);
passed = all(isfinite(error)) && maxAbs<=1e-3 && meanAbs<=1e-4 && ...
    sameIterations && residualDifference<=1e-6 && ...
    candidate.T.Converged && reference.T.Converged;
V = table(r,t,maxAbs,meanAbs,sameIterations,residualDifference,passed, ...
    'VariableNames',{'Repeat','NNThreads','MaxAbs','MeanAbs', ...
    'SameIterations','ResidualDifference','Passed'});
writetable(V,fullfile(outputRoot,'validation',sprintf('check_%03d.tsv',r)), ...
    'FileType','text','Delimiter','\t');
assert(passed,'Candidate differs from original 16-thread state beyond tolerance.');
end
