function aggregate = aggregate_near_zero_conditions(inputRoot, outputRoot)
% Aggregate the 16 angle/contrast near-zero condition audits.

if nargin < 1 || isempty(inputRoot)
    inputRoot = fullfile(fileparts(mfilename('fullpath')), 'results_full16');
end
if nargin < 2 || isempty(outputRoot)
    outputRoot = inputRoot;
end
if ~exist(outputRoot, 'dir'); mkdir(outputRoot); end

matrixFiles = dir(fullfile(inputRoot, 'near_zero_matrix_summary_*.tsv'));
proportionalityFiles = dir(fullfile(inputRoot, ...
    'near_zero_proportionality_*.tsv'));
auditFiles = dir(fullfile(inputRoot, 'near_zero_audit_*.tsv'));
if numel(matrixFiles) ~= 16 || numel(proportionalityFiles) ~= 16 || ...
        numel(auditFiles) ~= 16
    error('NearZeroAggregate:Inputs', ...
        'Expected 16 matrix, proportionality, and audit files.');
end

matrixAll = local_read_all(matrixFiles);
proportionalityAll = local_read_all(proportionalityFiles);
auditAll = local_read_all(auditFiles);

matrixNames = unique(matrixAll.matrix, 'stable');
matrixRows = cell(numel(matrixNames), 20);
for index = 1:numel(matrixNames)
    name = matrixNames{index};
    rows = matrixAll(strcmp(matrixAll.matrix, name), :);
    matrixRows(index, :) = {name, height(rows), ...
        min(rows.structuralRank), max(rows.structuralRank), ...
        min(rows.zeroColumns), max(rows.zeroColumns), ...
        min(rows.density), max(rows.density), ...
        min(rows.countAbsEigLE1e10), max(rows.countAbsEigLE1e10), ...
        min(rows.countAbsEigLE1e2), median(rows.countAbsEigLE1e2), ...
        max(rows.countAbsEigLE1e2), min(rows.countAbsEigLE2p5e2), ...
        median(rows.countAbsEigLE2p5e2), max(rows.countAbsEigLE2p5e2), ...
        min(rows.countAbsEigLE5e2), median(rows.countAbsEigLE5e2), ...
        max(rows.countAbsEigLE5e2), median(rows.fractionAbsEigLE5e2)};
end
matrixAggregate = cell2table(matrixRows, 'VariableNames', { ...
    'matrix', 'conditionCount', 'minimumStructuralRank', ...
    'maximumStructuralRank', 'minimumZeroColumns', 'maximumZeroColumns', ...
    'minimumDensity', 'maximumDensity', 'minimumExactZeroCount', ...
    'maximumExactZeroCount', 'minimumCountAbsEigLE1e2', ...
    'medianCountAbsEigLE1e2', 'maximumCountAbsEigLE1e2', ...
    'minimumCountAbsEigLE2p5e2', 'medianCountAbsEigLE2p5e2', ...
    'maximumCountAbsEigLE2p5e2', 'minimumCountAbsEigLE5e2', ...
    'medianCountAbsEigLE5e2', 'maximumCountAbsEigLE5e2', ...
    'medianFractionAbsEigLE5e2'});

proportionalityNames = unique(proportionalityAll.matrix, 'stable');
propRows = cell(numel(proportionalityNames), 10);
for index = 1:numel(proportionalityNames)
    name = proportionalityNames{index};
    rows = proportionalityAll(strcmp(proportionalityAll.matrix, name), :);
    propRows(index, :) = {name, height(rows), min(rows.bestScalarQ), ...
        median(rows.bestScalarQ), max(rows.bestScalarQ), ...
        min(rows.globalRelativeResidual), ...
        median(rows.globalRelativeResidual), ...
        max(rows.globalRelativeResidual), min(rows.minimumColumnScalarQ), ...
        max(rows.maximumColumnScalarQ)};
end
proportionalityAggregate = cell2table(propRows, 'VariableNames', { ...
    'matrix', 'conditionCount', 'minimumBestScalarQ', 'medianBestScalarQ', ...
    'maximumBestScalarQ', 'minimumRelativeResidual', ...
    'medianRelativeResidual', 'maximumRelativeResidual', ...
    'minimumColumnQAcrossConditions', 'maximumColumnQAcrossConditions'});

auditAggregate = table(height(auditAll), ...
    max(auditAll.reconstructionRelativeError), ...
    max(auditAll.J6ISourceFraction), max(auditAll.JINonISourceFraction), ...
    'VariableNames', {'conditionCount', 'maximumReconstructionRelativeError', ...
    'maximumJ6ISourceFraction', 'maximumJINonISourceFraction'});

writetable(matrixAll, fullfile(outputRoot, 'all_condition_matrix_rows.tsv'), ...
    'FileType', 'text', 'Delimiter', '\t');
writetable(proportionalityAll, fullfile(outputRoot, ...
    'all_condition_proportionality_rows.tsv'), ...
    'FileType', 'text', 'Delimiter', '\t');
writetable(matrixAggregate, fullfile(outputRoot, ...
    'near_zero_matrix_aggregate.tsv'), ...
    'FileType', 'text', 'Delimiter', '\t');
writetable(proportionalityAggregate, fullfile(outputRoot, ...
    'near_zero_proportionality_aggregate.tsv'), ...
    'FileType', 'text', 'Delimiter', '\t');
writetable(auditAggregate, fullfile(outputRoot, ...
    'near_zero_audit_aggregate.tsv'), ...
    'FileType', 'text', 'Delimiter', '\t');

aggregate = struct('MatrixRows', matrixAll, ...
    'ProportionalityRows', proportionalityAll, 'AuditRows', auditAll, ...
    'MatrixAggregate', matrixAggregate, ...
    'ProportionalityAggregate', proportionalityAggregate, ...
    'AuditAggregate', auditAggregate);
save(fullfile(outputRoot, 'near_zero_aggregate.mat'), 'aggregate', '-v7.3');
fprintf('Aggregated %d near-zero conditions.\n', height(auditAll));
end

function combined = local_read_all(files)
tables = cell(numel(files), 1);
for index = 1:numel(files)
    tables{index} = readtable(fullfile(files(index).folder, files(index).name), ...
        'FileType', 'text', 'Delimiter', '\t', 'VariableNamingRule', 'preserve');
end
combined = vertcat(tables{:});
end
