function allConditions = summarize_ji_component_structure(outputRoot)
% Combine the 16 inhibitory-source J_I audits and plot condition summaries.

if nargin < 1 || isempty(outputRoot)
    outputRoot = getenv('JI_OUTPUT_ROOT');
end
dataRoot = fullfile(outputRoot, 'data');
figureRoot = fullfile(outputRoot, 'figures');
files = dir(fullfile(dataRoot, 'ji_structure_angle*.tsv'));
if numel(files) ~= 16
    error('JIAnalysis:Incomplete', ...
        'Expected 16 condition tables in %s, found %d.', dataRoot, numel(files));
end

tables = cell(numel(files), 1);
for index = 1:numel(files)
    tables{index} = readtable(fullfile(files(index).folder, files(index).name), ...
        'FileType', 'text', 'Delimiter', '\t');
end
allConditions = sortrows(vertcat(tables{:}), {'contrast', 'angle'});
writetable(allConditions, fullfile(dataRoot, 'ji_structure_all_conditions.tsv'), ...
    'FileType', 'text', 'Delimiter', '\t');

metricNames = { ...
    'fullMaximumRealLambda'; ...
    'topRealNearestEigenvalueDistance'; ...
    'topRealPartGap'; ...
    'topRealCountWithin1e3'; ...
    'topRealIRoughness'; ...
    'topRealFourierTop4Fraction'; ...
    'spectralRadiusII'; ...
    'absoluteMagnitudeGapRatio'; ...
    'absoluteIRoughness'; ...
    'absoluteFourierTop4Fraction'; ...
    'sigma1'; ...
    'singularGapRatio'; ...
    'stableRank'};
minimum = zeros(numel(metricNames), 1);
medianValue = zeros(numel(metricNames), 1);
maximum = zeros(numel(metricNames), 1);
for index = 1:numel(metricNames)
    values = allConditions.(metricNames{index});
    minimum(index) = min(values, [], 'omitnan');
    medianValue(index) = median(values, 'omitnan');
    maximum(index) = max(values, [], 'omitnan');
end
rangeSummary = table(metricNames, minimum, medianValue, maximum, ...
    'VariableNames', {'metric', 'minimum', 'median', 'maximum'});
writetable(rangeSummary, fullfile(dataRoot, 'ji_metric_ranges.tsv'), ...
    'FileType', 'text', 'Delimiter', '\t');

if ~exist(figureRoot, 'dir'); mkdir(figureRoot); end
fig = figure('Visible', 'off', 'Color', 'w', 'Position', [40 40 1760 1320]);
layout = tiledlayout(fig, 3, 3, 'TileSpacing', 'compact', 'Padding', 'compact');
colormap(fig, parula(256));
local_heatmap(nexttile(layout), allConditions, 'fullMaximumRealLambda', ...
    'max Re(lambda(J_I))');
local_heatmap(nexttile(layout), allConditions, 'topRealCountWithin1e3', ...
    'K_{II} modes within 10^{-3} of top real part');
local_heatmap(nexttile(layout), allConditions, 'topRealIRoughness', ...
    'top-real I-map roughness');
local_heatmap(nexttile(layout), allConditions, 'topRealFourierTop4Fraction', ...
    'top-real I-map Fourier top-4 fraction');
local_heatmap(nexttile(layout), allConditions, 'spectralRadiusII', ...
    'rho(K_{II}) = max |lambda(J_I)|');
local_heatmap(nexttile(layout), allConditions, 'absoluteMagnitudeGapRatio', ...
    '|lambda|_1 / |lambda|_2');
local_heatmap(nexttile(layout), allConditions, 'absoluteIRoughness', ...
    'largest-|lambda| I-map roughness');
local_heatmap(nexttile(layout), allConditions, 'sigma1', ...
    'sigma_1(J_I)');
local_heatmap(nexttile(layout), allConditions, 'singularGapRatio', ...
    'sigma_1 / sigma_2');
title(layout, ...
    'Inhibitory-source J_I structure across orientation and contrast', ...
    'FontSize', 16, 'FontWeight', 'bold');
exportgraphics(fig, fullfile(figureRoot, 'ji_all_condition_summary.pdf'), ...
    'ContentType', 'vector');
close(fig);
end

function local_heatmap(axisHandle, conditionTable, metricName, titleText)
angles = unique(conditionTable.angle, 'sorted');
contrasts = unique(conditionTable.contrast, 'sorted');
[~, angleIndex] = ismember(conditionTable.angle, angles);
[~, contrastIndex] = ismember(conditionTable.contrast, contrasts);
values = accumarray([contrastIndex angleIndex], conditionTable.(metricName), ...
    [numel(contrasts) numel(angles)], @mean, NaN);
imagesc(axisHandle, angles, contrasts, values);
set(axisHandle, 'YDir', 'normal');
xlabel(axisHandle, 'orientation (deg)');
ylabel(axisHandle, 'contrast');
title(axisHandle, titleText, 'FontSize', 11, 'FontWeight', 'bold');
colorbar(axisHandle);
axis(axisHandle, 'tight');
end
