function aggregate_global_offset()
% Aggregate globally audited offsets and generate threshold-free figures.

outputRoot=getenv('GLOBAL_OFFSET_OUTPUT_ROOT');
oldSummaryFile=getenv('GLOBAL_OFFSET_OLD_SUMMARY');
fppSummaryFile=getenv('GLOBAL_OFFSET_FPP_SUMMARY');
if isempty(outputRoot) || ~exist(outputRoot,'dir') || ...
        ~isfile(oldSummaryFile) || ~isfile(fppSummaryFile)
    error('GlobalOffset:Environment','Required result files are missing.');
end
files=dir(fullfile(outputRoot,'*','case_summary.tsv'));
if isempty(files); error('GlobalOffset:NoResults','No case summaries found.'); end
parts=cell(numel(files),1);
scanParts=cell(numel(files),1);
for index=1:numel(files)
    parts{index}=readtable(fullfile(files(index).folder,files(index).name), ...
        'FileType','text','Delimiter','\t','TextType','string');
    profile=readtable(fullfile(files(index).folder,'global_search_profile.tsv'), ...
        'FileType','text','Delimiter','\t','TextType','string');
    profile=addvars(profile, ...
        repmat(parts{index}.taskId(1),height(profile),1), ...
        repmat(parts{index}.beta6(1),height(profile),1), ...
        'Before',1,'NewVariableNames',{'taskId','beta6'});
    scanParts{index}=profile;
end
summary=sortrows(vertcat(parts{:}),'beta6');
allScans=sortrows(vertcat(scanParts{:}),{'beta6','betaI'});
old=sortrows(readtable(oldSummaryFile,'FileType','text','Delimiter','\t', ...
    'TextType','string'),'beta6');
fpp=sortrows(readtable(fppSummaryFile,'FileType','text','Delimiter','\t', ...
    'TextType','string'),'beta6');
[oldMatched,oldRows]=ismembertol(summary.beta6,old.beta6,1e-12, ...
    'DataScale',1);
oldOverlap=old(oldRows(oldMatched),:);
summaryOverlap=summary(oldMatched,:);
if any(~summary.converged) || any(summary.boundaryMinimum)
    error('GlobalOffset:Audit','A global-best result failed convergence or hit a boundary.');
end
writetable(summary,fullfile(outputRoot,'global_best_offset_summary.tsv'), ...
    'FileType','text','Delimiter','\t');
writetable(allScans,fullfile(outputRoot,'all_betaI_scan_points.tsv'), ...
    'FileType','text','Delimiter','\t');

positive=summary.beta6>0;
x=summary.beta6(positive); y=summary.betaI(positive);
realSlope=dot(x,y)/dot(x,x);
realResidual=y-realSlope*x;
realR2=1-sum(realResidual.^2)/sum(y.^2);
fppPositive=fpp.beta6>0;
fppSlope=dot(fpp.beta6(fppPositive),fpp.betaI(fppPositive))/ ...
    dot(fpp.beta6(fppPositive),fpp.beta6(fppPositive));
theorySlope=fpp.theoreticalSlope(1);
betaIDifference=summaryOverlap.betaI-oldOverlap.betaI;
hcImprovement=oldOverlap.HCnorm-summaryOverlap.HCnorm;
metrics=table(["global_best_real_slope";"global_best_real_r2"; ...
    "fpp_numeric_slope";"theoretical_stability_slope"; ...
    "beta6_condition_count";"total_betaI_HC_evaluations"; ...
    "converged_betaI_HC_evaluations";"nonconverged_betaI_evaluations"; ...
    "maximum_absolute_betaI_change_from_old"; ...
    "maximum_HCnorm_improvement_from_old"; ...
    "minimum_boundary_gap";"maximum_search_evaluations"], ...
    [realSlope;realR2;fppSlope;theorySlope;height(summary);height(allScans); ...
    sum(allScans.converged);sum(~allScans.converged); ...
    max(abs(betaIDifference)); ...
    max(hcImprovement);min(summary.boundaryGap(summary.beta6>0)); ...
    max(summary.searchEvaluations)],'VariableNames',{'metric','value'});
writetable(metrics,fullfile(outputRoot,'global_best_offset_metrics.tsv'), ...
    'FileType','text','Delimiter','\t');

figureRoot=fullfile(outputRoot,'figures');
if ~exist(figureRoot,'dir'); mkdir(figureRoot); end
lineX=linspace(0,max(summary.beta6),300);
fig=figure('Visible','off','Color','w','Position',[80 80 1280 820]);
hold on; grid on;
plotScans=allScans(allScans.converged & isfinite(allScans.HCnorm) & ...
    allScans.HCnorm>0 & allScans.betaI>=0,:);
failedScans=allScans(~allScans.converged & allScans.betaI>=0,:);
scanPoints=scatter(plotScans.beta6,plotScans.betaI,34,plotScans.HCnorm, ...
    'filled','MarkerFaceAlpha',0.90,'MarkerEdgeAlpha',0.90, ...
    'DisplayName','attempted betaI >= 0; color = HCnorm');
if ~isempty(failedScans)
    scatter(failedScans.beta6,failedScans.betaI,24,[0.45 0.45 0.45],'x', ...
        'DisplayName','attempted betaI without converged fixed point');
end
plot(lineX,theorySlope*lineX,'k--','LineWidth',1.8, ...
    'DisplayName',sprintf('theoretical local stability slope %.6f',theorySlope));
xlabel('\beta_6 (fractional whole-L6 increase)');
ylabel('\beta_I (fractional whole-inhibition increase)');
title({'Extended betaI scan and global-best real fixed-point cancellation', ...
    'Nonnegative attempted betaI values are shown; no HCnorm threshold is applied', ...
    'HCnorm = HC_norm_diff with wC = 0.3077, aE = 0.8, aI = 0.2'}, ...
    'Interpreter','none','FontWeight','bold');
legend('Location','northwest','Interpreter','none');
colormap(fig,parula); ax=gca; ax.ColorScale='log';
positiveBeta6HC=plotScans.HCnorm(plotScans.beta6>0);
clim([min(positiveBeta6HC) max(plotScans.HCnorm)]);
cb=colorbar; cb.Label.String='HCnorm (logarithmic color scale)';
scanPoints.MarkerEdgeColor='none';
local_save(fig,figureRoot,'07_GlobalBest_Real_vs_FPP_vs_Theoretical_Offset');

fig=figure('Visible','off','Color','w','Position',[80 80 1120 720]);
plot(oldOverlap.beta6,oldOverlap.HCnorm,'o-','Color',[0.55 0.55 0.55], ...
    'LineWidth',1.5,'MarkerSize',5,'DisplayName','previous fminbnd minimum');
hold on; grid on;
plot(summary.beta6,summary.HCnorm,'s-','Color',[0.08 0.42 0.72], ...
    'LineWidth',2,'MarkerSize',4,'DisplayName','globally audited minimum');
xlabel('\beta_6 (fractional whole-L6 increase)');
ylabel('minimum verified HCnorm');
title({'Best achievable canonical HCnorm with one global inhibition gain', ...
    'Extended beta6 range 0 to 0.25; all minima retained without thresholding', ...
    'HCnorm = HC_norm_diff with wC = 0.3077, aE = 0.8, aI = 0.2', ...
    sprintf('comparison to previous search uses %d overlapping beta6 values', ...
    height(oldOverlap))}, ...
    'Interpreter','none','FontWeight','bold');
legend('Location','northwest','Interpreter','none');
local_save(fig,figureRoot,'08_GlobalBest_Minimum_HCnorm_vs_Beta6');

profileTargets=[0.01 0.05 0.10 0.15 0.20 0.25];
fig=figure('Visible','off','Color','w','Position',[80 80 1380 920]);
layout=tiledlayout(fig,2,3,'TileSpacing','loose','Padding','loose');
layout.OuterPosition=[0.03 0.03 0.94 0.90];
for targetIndex=1:numel(profileTargets)
    target=profileTargets(targetIndex);
    [~,row]=min(abs(summary.beta6-target));
    caseDir=sprintf('%03d_beta6_%s',summary.taskId(row),number_tag(summary.beta6(row)));
    profile=readtable(fullfile(outputRoot,caseDir,'global_search_profile.tsv'), ...
        'FileType','text','Delimiter','\t','TextType','string');
    ax=nexttile(layout); semilogy(ax,profile.betaI,profile.HCnorm,'.-', ...
        'Color',[0.25 0.55 0.75],'MarkerSize',8,'LineWidth',0.7);
    hold(ax,'on'); grid(ax,'on');
    plot(ax,summary.betaI(row),summary.HCnorm(row), ...
        'p','MarkerSize',13,'MarkerFaceColor',[0.85 0.33 0.10], ...
        'MarkerEdgeColor','k');
    xlabel(ax,'betaI'); ylabel(ax,'HCnorm');
    title(ax,sprintf('beta6 = %.3f; best betaI = %.8f', ...
        summary.beta6(row),summary.betaI(row)),'Interpreter','none');
end
annotation(fig,'textbox',[0.05 0.95 0.90 0.035], ...
    'String',['Canonical HCnorm profiles: HC_norm_diff, wC = 0.3077, ' ...
    'aE = 0.8, aI = 0.2'], ...
    'HorizontalAlignment','center','VerticalAlignment','middle', ...
    'FontWeight','bold','FontSize',14,'LineStyle','none','Interpreter','none');
local_save(fig,figureRoot,'09_GlobalBest_HCnorm_Search_Profiles');

save(fullfile(outputRoot,'global_best_offset_results.mat'),'summary','allScans', ...
    'old','oldOverlap','summaryOverlap', ...
    'fpp','metrics','realSlope','realR2','fppSlope','theorySlope', ...
    'betaIDifference','hcImprovement','-v7.3');
fprintf(['Global-best offset: real slope %.9f; max betaI change %.3e; ' ...
    'max HC improvement %.3e.\n'],realSlope,max(abs(betaIDifference)), ...
    max(hcImprovement));
end

function local_save(fig,root,stem)
savefig(fig,fullfile(root,[stem '.fig']));
exportgraphics(fig,fullfile(root,[stem '.pdf']),'ContentType','vector');
close(fig);
end

function tag=number_tag(value)
tag=sprintf('%+.5f',value);
tag=strrep(tag,'+','p'); tag=strrep(tag,'-','m'); tag=strrep(tag,'.','p');
end
