function summary = run_spatial_shape_control_task(taskIndex,setupFile,outputRoot)
% Compare circular, one-sided, and triangular spatial footprints.

if nargin < 1 || isempty(taskIndex)
    taskIndex = str2double(getenv('SLURM_ARRAY_TASK_ID'));
end
if nargin < 2 || isempty(setupFile)
    setupFile = getenv('SPATIAL_CONTROL_SETUP');
end
if nargin < 3 || isempty(outputRoot)
    outputRoot = getenv('SPATIAL_CONTROL_OUTPUT');
end
if ~exist(outputRoot,'dir'); mkdir(outputRoot); end

controls = table( ...
    ["baseline";"left_half";"baseline";"left_half"; ...
     "triangle";"baseline";"triangle"], ...
    ["baseline";"baseline";"left_half";"left_half"; ...
     "baseline";"triangle";"triangle"], ...
    ["baseline";"L4_left_half";"L6_left_half";"joint_left_half"; ...
     "L4_triangle";"L6_triangle";"joint_triangle"], ...
    'VariableNames',{'l4Shape','l6Shape','control'});
if taskIndex<1 || taskIndex>height(controls)
    error('SpatialShape:Task','Task index must be 1--%d.',height(controls));
end

loaded = load(setupFile,'setup');
setup = loaded.setup;
control = controls(taskIndex,:);
[J,details] = l6ns_spatial_shape_control_jacobian(setup, ...
    control.l4Shape,control.l6Shape);
if taskIndex==1
    baselineError = norm(J-setup.Pathway.JBaseline,'fro')/ ...
        max(norm(setup.Pathway.JBaseline,'fro'),eps);
    if baselineError>1e-10
        error('SpatialShape:Baseline','Baseline reconstruction error %.3e.',baselineError);
    end
else
    baselineError = norm(J-setup.Pathway.JBaseline,'fro')/ ...
        max(norm(setup.Pathway.JBaseline,'fro'),eps);
end

fprintf('%s: full eigendecomposition and SVD.\n',control.control);
eigenvalues = eig(full(J),'vector');
singularValues = svd(full(J));
n = size(J,1)/3;
e = 1:2*n;
i = 2*n+(1:n);
A = sparse(J(e,e)); B = sparse(J(e,i));
C = sparse(J(i,e)); D = sparse(J(i,i));
X = A\B;
H = sparse(D-C*X);
schurEigenvalues = eig(full(H),'vector');

frobeniusNorm = norm(singularValues);
energy = singularValues.^2/frobeniusNorm^2;
henriciDeparture = sqrt(max(0,frobeniusNorm^2-sum(abs(eigenvalues).^2)))/ ...
    max(frobeniusNorm,eps);
summary = table(taskIndex,control.control,control.l4Shape,control.l6Shape, ...
    baselineError,max(real(eigenvalues)),min(real(eigenvalues)), ...
    sum(abs(eigenvalues)<=0.01),sum(abs(eigenvalues)<=0.025), ...
    sum(abs(eigenvalues)<=0.05),sum(singularValues<=0.01), ...
    sum(singularValues<=0.025),sum(singularValues<=0.05), ...
    sum(abs(schurEigenvalues)<=0.01),sum(abs(schurEigenvalues)<=0.025), ...
    sum(abs(schurEigenvalues)<=0.05), ...
    frobeniusNorm^2/singularValues(1)^2, ...
    exp(-sum(energy.*log(max(energy,realmin)))),henriciDeparture, ...
    details.L4RowSumRelativeError,details.L4TranslationError, ...
    details.L4Rotation90Error,details.L4Rotation180Error, ...
    details.L4ReflectionError,details.L4RetainedMassFraction, ...
    details.L4TriangleRadius,details.L6RowSumRelativeError, ...
    details.L6TranslationError,details.L6Rotation90Error, ...
    details.L6Rotation180Error,details.L6ReflectionError, ...
    details.L6RetainedMassFraction,details.L6TriangleRadius, ...
    'VariableNames',{'taskIndex','control','l4Shape','l6Shape', ...
    'relativeBaselineChange','maximumRealEigenvalue','minimumRealEigenvalue', ...
    'countAbsEigLE0p01','countAbsEigLE0p025','countAbsEigLE0p05', ...
    'countSingularLE0p01','countSingularLE0p025','countSingularLE0p05', ...
    'countSchurEigLE0p01','countSchurEigLE0p025','countSchurEigLE0p05', ...
    'stableRank','entropyEffectiveRank','henriciDeparture', ...
    'l4RowSumRelativeError','l4TranslationError','l4Rotation90Error', ...
    'l4Rotation180Error','l4ReflectionError','l4RetainedMassFraction', ...
    'l4TriangleRadius','l6RowSumRelativeError','l6TranslationError', ...
    'l6Rotation90Error','l6Rotation180Error','l6ReflectionError', ...
    'l6RetainedMassFraction','l6TriangleRadius'});

tag = char(control.control);
writetable(summary,fullfile(outputRoot,['shape_' tag '.tsv']), ...
    'FileType','text','Delimiter','\t');
l4Kernel = details.L4Kernel;
l6Kernel = details.L6Kernel;
save(fullfile(outputRoot,['shape_' tag '.mat']), ...
    'summary','eigenvalues','singularValues','schurEigenvalues', ...
    'l4Kernel','l6Kernel','-v7.3');
fprintf('%s: eig/sigma/Schur <=.05 %d/%d/%d.\n',tag, ...
    summary.countAbsEigLE0p05,summary.countSingularLE0p05, ...
    summary.countSchurEigLE0p05);
end
