function generate_sc_reduction_near_zero_comparison()
% Compare near-zero counts before and after combining S and C.

analysisRoot = repro_paths('project/Spectral_Analysis/matlab-inserting_into_CG_model/l6_next_stage_analysis_20260717');
fullFile = fullfile(analysisRoot, 'near_zero_clustering_20260722', ...
    'results_full16', 'all_condition_matrix_rows.tsv');
reducedRoot = fullfile(analysisRoot, '..', ...
    'Complete_Code_for_Paper3', 'NYU-Vision-2Drive-main', 'Figures', ...
    'spectral_analysis_eigenvalue_eigenvectors', 'L6 and Inhibition', ...
    'Eigenspectrum_for_all_Jacobians_3200');
outputRoot = [[repro_paths('project') '/'] ...
    'Spectral_Analysis_Report/10_near 0 cluster reason'];

angles = [0 7.5 15 22.5];
contrast = 100;
threshold = 0.05;

if ~isfile(fullFile)
    error('Missing full-system summary: %s', fullFile);
end
if ~exist(outputRoot, 'dir')
    mkdir(outputRoot);
end

fullTable = readtable(fullFile, 'FileType', 'text', 'Delimiter', '\t', ...
    'VariableNamingRule', 'preserve');
fullCounts = nan(size(angles));
reducedCounts = nan(size(angles));

for conditionIndex = 1:numel(angles)
    angle = angles(conditionIndex);
    fullRow = strcmp(fullTable.matrix, 'J_baseline') & ...
        abs(fullTable.angleDeg - angle) < 1e-10 & ...
        fullTable.contrast == contrast;
    if nnz(fullRow) ~= 1
        error('Expected one full-system row for angle %.2f.', angle);
    end
    fullCounts(conditionIndex) = fullTable.countAbsEigLE5e2(fullRow);

    angleToken = strrep(sprintf('%.2f', angle), '.', 'p');
    reducedFile = fullfile(reducedRoot, sprintf( ...
        'manifest_l6_angle%s_contrast%d.tsv', angleToken, contrast));
    if ~isfile(reducedFile)
        error('Missing reduced-system manifest: %s', reducedFile);
    end
    reducedTable = readtable(reducedFile, 'FileType', 'text', ...
        'Delimiter', '\t', 'VariableNamingRule', 'preserve');
    reducedRow = strcmp(reducedTable.jacobian, 'Total J(w)') & ...
        strcmp(reducedTable.state, 'Dynamic_L6_w0');
    if nnz(reducedRow) ~= 1
        error('Expected one reduced baseline row for angle %.2f.', angle);
    end
    reducedCounts(conditionIndex) = ...
        reducedTable.countAbsLambdaLe0p05(reducedRow);
end

removedCounts = fullCounts - reducedCounts;
summaryTable = table(angles(:), repmat(contrast, numel(angles), 1), ...
    fullCounts(:), reducedCounts(:), removedCounts(:), ...
    'VariableNames', {'angleDeg','contrast','full4800Count', ...
    'reduced3200Count','removedBySCReduction'});
writetable(summaryTable, fullfile(outputRoot, ...
    '10.1_Count_Removed_by_SC_Reduction_Data.tsv'), ...
    'FileType', 'text', 'Delimiter', '\t');

fullColor = [0.18 0.47 0.72];
reducedColor = [0.88 0.43 0.16];
connectorColor = [0.28 0.28 0.28];

fig = figure('Visible', 'off', 'Color', 'w', ...
    'Position', [80 80 1500 880]);
ax = axes(fig);
hold(ax, 'on');

x = 1:numel(angles);
barWidth = 0.31;
offset = 0.18;
bar(ax, x - offset, fullCounts, barWidth, 'FaceColor', fullColor, ...
    'EdgeColor', 'none', 'DisplayName', 'Full S-C-I system (4,800 states)');
bar(ax, x + offset, reducedCounts, barWidth, 'FaceColor', reducedColor, ...
    'EdgeColor', 'none', 'DisplayName', 'Reduced E-I system (3,200 states)');

for conditionIndex = 1:numel(x)
    plot(ax, [x(conditionIndex)-offset, x(conditionIndex)+offset], ...
        [fullCounts(conditionIndex), reducedCounts(conditionIndex)], ...
        '-', 'Color', connectorColor, 'LineWidth', 1.6, ...
        'HandleVisibility', 'off');
    plot(ax, x(conditionIndex)-offset, fullCounts(conditionIndex), ...
        'o', 'MarkerSize', 5, 'MarkerFaceColor', fullColor, ...
        'MarkerEdgeColor', connectorColor, 'HandleVisibility', 'off');
    plot(ax, x(conditionIndex)+offset, reducedCounts(conditionIndex), ...
        'o', 'MarkerSize', 5, 'MarkerFaceColor', reducedColor, ...
        'MarkerEdgeColor', connectorColor, 'HandleVisibility', 'off');

    text(ax, x(conditionIndex), ...
        0.5 * (fullCounts(conditionIndex) + reducedCounts(conditionIndex)), ...
        sprintf('\\DeltaN_{0.05} = %s', ...
        stringWithThousandsSeparator(removedCounts(conditionIndex))), ...
        'HorizontalAlignment', 'center', 'VerticalAlignment', 'middle', ...
        'FontSize', 12, 'FontWeight', 'bold', 'Color', connectorColor, ...
        'BackgroundColor', 'w', 'Margin', 3);

    text(ax, x(conditionIndex)-offset, fullCounts(conditionIndex)+60, ...
        stringWithThousandsSeparator(fullCounts(conditionIndex)), ...
        'HorizontalAlignment', 'center', 'FontSize', 10, ...
        'Color', fullColor, 'FontWeight', 'bold');
    text(ax, x(conditionIndex)+offset, reducedCounts(conditionIndex)-90, ...
        stringWithThousandsSeparator(reducedCounts(conditionIndex)), ...
        'HorizontalAlignment', 'center', 'FontSize', 10, ...
        'Color', 'w', 'FontWeight', 'bold');
end

meanRemoved = mean(removedCounts);

xlim(ax, [0.5 4.5]);
ylim(ax, [0 3250]);
xticks(ax, x);
xticklabels(ax, compose('%.1f^\\circ', angles));
xlabel(ax, 'Stimulus orientation (contrast 100)');
ylabel(ax, sprintf('Number of eigenvalues with |\\lambda| \\leq %.2f', threshold));
title(ax, {'Near-zero modes removed by S/C population reduction', ...
    sprintf(['Full 4,800-state S-C-I system versus reduced 3,200-state E-I system; ' ...
    'mean removed = %.1f'], meanRemoved)}, ...
    'FontSize', 16, 'FontWeight', 'bold');
text(ax, 4.42, 3135, sprintf('Removed range: %s-%s (approximately 1,600)', ...
    stringWithThousandsSeparator(min(removedCounts)), ...
    stringWithThousandsSeparator(max(removedCounts))), ...
    'HorizontalAlignment', 'right', 'VerticalAlignment', 'top', ...
    'FontSize', 11, 'FontWeight', 'bold', 'Color', connectorColor, ...
    'BackgroundColor', 'w', 'Margin', 4);
legend(ax, 'Location', 'southwest', 'FontSize', 11);
grid(ax, 'on');
ax.GridAlpha = 0.15;
ax.YGrid = 'on';
ax.XGrid = 'off';
ax.FontSize = 12;
box(ax, 'on');

pdfFile = fullfile(outputRoot, ...
    '10.1_Count_Removed_by_SC_Reduction.pdf');
figFile = fullfile(outputRoot, ...
    '10.1_Count_Removed_by_SC_Reduction.fig');
exportgraphics(fig, pdfFile, 'ContentType', 'vector');
savefig(fig, figFile);
close(fig);

fprintf('Saved %s\n', pdfFile);
fprintf('Saved %s\n', figFile);
fprintf('Removed counts: %s; mean %.2f\n', ...
    strjoin(arrayfun(@stringWithThousandsSeparator, removedCounts, ...
    'UniformOutput', false), ', '), meanRemoved);
end

function output = stringWithThousandsSeparator(value)
output = regexprep(sprintf('%d', round(value)), ...
    '(?<=\d)(?=(\d{3})+$)', ',');
end
