function plot_three_hcnorm3_boundaries()
% Replot the three pathway-offset HCnorm heatmaps with the 3 Hz boundary.

figureBase = fullfile( ...
    [repro_paths('project') '/Spectral_Analysis'], ...
    'matlab-inserting_into_CG_model/Complete_Code_for_Paper3', ...
    'NYU-Vision-2Drive-main/Figures/spectral_analysis_eigenvalue_eigenvectors', ...
    'L6 and Inhibition');
hcAudit = readtable(fullfile(figureBase, ...
    'theoretical_hc_optimal_fixedpoint_slope_audit.tsv'), ...
    'FileType','text','Delimiter','\t');
hcSlopes = struct( ...
    'L6Inhibition',hcAudit.slopeL6Inhibition(end), ...
    'L6Excitation',hcAudit.slopeL6Excitation(end), ...
    'ExcitationInhibition',hcAudit.slopeExcitationInhibition(end));
unacceptedHCThreshold = 170;
commonColorLimits = local_shared_color_limits( ...
    figureBase, unacceptedHCThreshold);

local_plot_l6_inhibition(fullfile(figureBase, 'L6_and_Inhibition_offset'), ...
    hcSlopes.L6Inhibition, ...
    commonColorLimits, unacceptedHCThreshold);
local_plot_pair(fullfile(figureBase, 'L6_and_Excitation_offset'), ...
    '\beta_6 (fractional whole-L6 increase)', ...
    '\beta_E (fractional recurrent-excitation change)', ...
    '08_FullGrid_Beta6_BetaE_Canonical_HCnorm_Heatmap_with_HCnorm3_Boundary', ...
    hcSlopes.L6Excitation, ...
    commonColorLimits, unacceptedHCThreshold);
local_plot_pair(fullfile(figureBase, 'Excitation_and_Inhibition_offset'), ...
    '\beta_E (fractional recurrent-excitation increase)', ...
    '\beta_I (fractional whole-inhibition increase)', ...
    '09_FullGrid_BetaE_BetaI_Canonical_HCnorm_Heatmap_with_HCnorm3_Boundary', ...
    hcSlopes.ExcitationInhibition, ...
    commonColorLimits, unacceptedHCThreshold);
end

function local_plot_l6_inhibition(outputRoot, hcSlope, ...
        commonColorLimits, unacceptedHCThreshold)
data = load(fullfile(outputRoot, 'full_grid_results.mat'), ...
    'beta6Values', 'betaIValues', 'hcMatrix', 'validHC', ...
    'residualMatrix');
plotHC = local_accept_all_finite_hc(data);
[fig, hUnaccepted] = local_heatmap( ...
    data.beta6Values, data.betaIValues, plotHC, ...
    '\beta_6 (fractional whole-L6 increase)', ...
    '\beta_I (fractional whole-inhibition increase)', ...
    commonColorLimits, unacceptedHCThreshold);
ax = gca;
hold(ax, 'on');
hHc = local_add_theory_line(ax, data.beta6Values, data.betaIValues, ...
    hcSlope, '--', 'moved-FP HC', [0.75 0 0.75]);
hRegression = local_add_best_hc_regression(ax, data.beta6Values, ...
    data.betaIValues, data.validHC);
hBoundary = local_add_boundary(ax, data.beta6Values, data.betaIValues, ...
    data.validHC);
hBoundary10 = local_add_hc10_boundary( ...
    ax, data.beta6Values, data.betaIValues, plotHC);
local_legend(ax, hHc, hRegression, hBoundary, hBoundary10, ...
    hUnaccepted, hcSlope, unacceptedHCThreshold);
local_save(fig, outputRoot, ...
    '07_FullGrid_Beta6_BetaI_Canonical_HCnorm_Heatmap_with_HCnorm3_Boundary');
end

function local_legend(ax, hHc, hRegression, hBoundary, ...
        hBoundary10, hUnaccepted, hcSlope, ...
        unacceptedHCThreshold)
regressionSlope = hRegression.UserData;
legend(ax, [hHc hRegression hBoundary hBoundary10 hUnaccepted], ...
    {sprintf('moved-FP HC slope %.6f', hcSlope), ...
    sprintf('minimum-HC regression %.6f', regressionSlope), ...
    'HC norm = 2 Hz', ...
    'HC norm = 5 Hz', ...
    sprintf('HC norm > %g Hz (unaccepted)', unacceptedHCThreshold)}, ...
    'Location', 'northoutside', 'Orientation', 'horizontal', ...
    'NumColumns', 3, ...
    'FontSize', 11.5, 'FontWeight', 'bold', 'Box', 'off');
end

function local_plot_pair(outputRoot, xLabel, yLabel, stem, hcSlope, ...
        commonColorLimits, unacceptedHCThreshold)
data = load(fullfile(outputRoot, 'full_grid_results.mat'));
if isfield(data, 'betaXValues')
    xValues = data.betaXValues;
    yValues = data.betaYValues;
else
    xValues = data.betaValues;
    yValues = data.betaValues;
end
acceptedHC = local_accept_all_finite_hc(data);
plotHC = data.plotHC;
newlyAccepted = isfinite(acceptedHC) & ~isfinite(plotHC);
plotHC(newlyAccepted) = acceptedHC(newlyAccepted);
[fig, hUnaccepted] = local_heatmap(xValues, yValues, plotHC, ...
    xLabel, yLabel, commonColorLimits, unacceptedHCThreshold);
ax = gca;
hold(ax, 'on');
hHc = local_add_theory_line(ax, xValues, yValues, hcSlope, ...
    '--', 'moved-FP HC', [0.75 0 0.75]);
hRegression = local_add_best_hc_regression(ax, xValues, yValues, ...
    data.validHC);
hBoundary = local_add_boundary(ax, xValues, yValues, ...
    data.validHC);
hBoundary10 = local_add_hc10_boundary(ax, xValues, yValues, plotHC);
local_legend(ax, hHc, hRegression, hBoundary, hBoundary10, ...
    hUnaccepted, hcSlope, unacceptedHCThreshold);
local_save(fig, outputRoot, stem);
end

function validHC = local_accept_all_finite_hc(data)
validHC = data.validHC;
accepted = isfinite(data.hcMatrix) & data.hcMatrix >= 0;
validHC(accepted) = data.hcMatrix(accepted);
fprintf('Accepted all finite-HC points: %d/%d (%d newly colored).\n', ...
    nnz(accepted), numel(accepted), ...
    nnz(accepted & ~isfinite(data.validHC)));
end

function hRegression = local_add_best_hc_regression(ax, xValues, ...
        yValues, validHC)
bestY = nan(size(xValues));
for xIndex = 1:numel(xValues)
    columnHC = validHC(:, xIndex);
    finiteRows = find(isfinite(columnHC));
    if isempty(finiteRows)
        continue;
    end
    [~, localIndex] = min(columnHC(finiteRows));
    bestY(xIndex) = yValues(finiteRows(localIndex));
end

fitMask = isfinite(bestY) & isfinite(xValues);
fitX = xValues(fitMask);
fitY = bestY(fitMask);
regressionSlope = sum(fitX .* fitY) / sum(fitX .^ 2);
hRegression = local_add_theory_line(ax, xValues, yValues, ...
    regressionSlope, '-', 'minimum-HC regression', [0.35 0.35 0.35]);
hRegression.UserData = regressionSlope;
fprintf('Minimum-HC regression slope: %.12g\n', regressionSlope);
end

function hTheory = local_add_theory_line(ax, xValues, yValues, slope, ...
        lineStyle, label, lineColor)
lineX = linspace(min(xValues), max(xValues), 500);
lineY = slope * lineX;
inside = lineY >= min(yValues) & lineY <= max(yValues);
if nargin < 7
    hTheory = plot(ax, lineX(inside), lineY(inside), lineStyle, ...
        'LineWidth', 2.2, 'DisplayName', ...
        sprintf('%s slope %.6f', label, slope));
else
    hTheory = plot(ax, lineX(inside), lineY(inside), lineStyle, ...
        'Color', lineColor, 'LineWidth', 2.2, 'DisplayName', ...
        sprintf('%s slope %.6f', label, slope));
end
end

function [fig, hUnaccepted] = local_heatmap(xValues, yValues, plotHC, ...
        xLabel, yLabel, commonColorLimits, unacceptedHCThreshold)
fig = figure('Visible', 'off', 'Color', 'w', 'Position', [80 80 1280 1020]);
unacceptedMask = isfinite(plotHC) & plotHC > unacceptedHCThreshold;
acceptedHC = plotHC;
acceptedHC(unacceptedMask) = NaN;
heatmapImage = imagesc(xValues, yValues, acceptedHC);
heatmapImage.AlphaData = isfinite(acceptedHC);
ax = gca;
set(ax, 'YDir', 'normal', 'Color', [0.80 0.80 0.80]);
axis(ax, 'xy');
axis(ax, 'tight');
xlabel(ax, xLabel, 'FontSize', 22, 'FontWeight', 'bold');
ylabel(ax, yLabel, 'FontSize', 22, 'FontWeight', 'bold');
set(ax, 'FontSize', 19, 'FontWeight', 'bold', 'LineWidth', 1.25, ...
    'XGrid', 'off', 'YGrid', 'off', 'ColorScale', 'log');
colormap(fig, jet);
clim(ax, commonColorLimits);
hold(ax, 'on');
unacceptedGray = 0.45;
grayRGB = repmat(unacceptedGray, [size(plotHC) 3]);
grayLayer = imagesc(ax, xValues, yValues, grayRGB);
grayLayer.AlphaData = double(unacceptedMask);
hUnaccepted = plot(ax, nan, nan, 's', 'MarkerSize', 9, ...
    'MarkerFaceColor', unacceptedGray * [1 1 1], ...
    'MarkerEdgeColor', unacceptedGray * [1 1 1]);
cb = colorbar(ax);
cb.FontSize = 17;
cb.Label.String = 'HC norm';
cb.Label.FontSize = 19;
cb.Label.FontWeight = 'bold';
cb.Title.String = 'Hz';
cb.Title.FontSize = 17;
cb.Title.FontWeight = 'bold';
end

function commonColorLimits = local_shared_color_limits( ...
        figureBase, unacceptedHCThreshold)
subfolders = {'L6_and_Inhibition_offset', ...
    'L6_and_Excitation_offset', 'Excitation_and_Inhibition_offset'};
finiteValues = [];
for index = 1:numel(subfolders)
    data = load(fullfile(figureBase, subfolders{index}, ...
        'full_grid_results.mat'), 'hcMatrix');
    values = data.hcMatrix(isfinite(data.hcMatrix) & ...
        data.hcMatrix > 0 & data.hcMatrix <= unacceptedHCThreshold);
    finiteValues = [finiteValues; values(:)]; %#ok<AGROW>
end
finiteValues = sort(finiteValues);
lowerIndex = max(1, ...
    round(0.001 * (numel(finiteValues) - 1)) + 1);
commonColorLimits = [finiteValues(lowerIndex) finiteValues(end)];
fprintf('Shared HC color limits: %.12g to %.12g Hz.\n', ...
    commonColorLimits(1), commonColorLimits(2));
end

function hBoundary = local_add_boundary(ax, xValues, yValues, validHC)
[~, hBoundary] = contour(ax, xValues, yValues, validHC, [2 2], ...
    'LineColor', 'k', 'LineWidth', 1.25, ...
    'DisplayName', 'HC norm = 2 Hz boundary');
end

function hBoundary10 = local_add_hc10_boundary( ...
        ax, xValues, yValues, plotHC)
[~, hBoundary10] = contour(ax, xValues, yValues, plotHC, [5 5], ...
    'LineColor', [0.20 0.20 0.20], 'LineStyle', '--', ...
    'LineWidth', 0.9, 'DisplayName', 'HC norm = 5 Hz boundary');
end

function local_save(fig, outputRoot, stem)
savefig(fig, fullfile(outputRoot, [stem '.fig']));
exportgraphics(fig, fullfile(outputRoot, [stem '.pdf']), ...
    'ContentType', 'vector');
close(fig);
end
