% Minimal executable check of the endpoint data and sparse eigensolver path.
cfg=l6ns_config();
data=l6ns_load_endpoints(cfg);
[maxRealW0,lambdaW0]=l6ns_max_real(data.J0,cfg);
[maxRealW1,lambdaW1]=l6ns_max_real(data.A,cfg);
smoke=table(data.Dimension,nnz(data.A),nnz(data.B),data.EndpointAffineError, ...
    data.FixedPointEndpointDifference,maxRealW0,real(lambdaW0),imag(lambdaW0), ...
    maxRealW1,real(lambdaW1),imag(lambdaW1), ...
    'VariableNames',{'dimension','nnzA','nnzB','affineError','fixedPointEndpointDifference', ...
    'maxRealW0','lambdaW0Real','lambdaW0Imag','maxRealW1','lambdaW1Real','lambdaW1Imag'});
writetable(smoke,fullfile(cfg.OutputRoot,'endpoint_smoke.tsv'), ...
    'FileType','text','Delimiter','\t');
disp(smoke);
