function write_l6ns_branch_atlas_report(root)
% Generate a concise evidence-audited Markdown report from atlas tables.

if nargin<1 || isempty(root); root=pwd; end
atlasDir=fullfile(root,'branch_atlas_20260803');
aggregateDir=fullfile(atlasDir,'aggregate');
components=readtable(fullfile(aggregateDir,'connected_components.tsv'), ...
    'FileType','text','Delimiter','\t');
tasks=readtable(fullfile(aggregateDir,'continuation_tasks.tsv'), ...
    'FileType','text','Delimiter','\t');
events=readtable(fullfile(aggregateDir,'event_candidates.tsv'), ...
    'FileType','text','Delimiter','\t');
symmetry=readtable(fullfile(atlasDir,'symmetry_candidate_audit.tsv'), ...
    'FileType','text','Delimiter','\t');
sectors=readtable(fullfile(atlasDir,'persistent_symmetry_sector_spectra.tsv'), ...
    'FileType','text','Delimiter','\t');
outputFile=fullfile(atlasDir,'UPDATED_BIFURCATION_REPORT.md');
file=fopen(outputFile,'w');
cleanup=onCleanup(@()fclose(file)); %#ok<NASGU>
fprintf(file,'# Updated bifurcation report\n\n');
fprintf(file,'## Scope and numerical controls\n\n');
fprintf(file,['This Phase I atlas uses the canonical h96 map and an arbitrary-state ', ...
    'analytic Jacobian. At the persistent state it reproduces the established ', ...
    'Jacobian exactly. Weighted pseudo-arclength uses population RMS scaling ', ...
    'and stores residuals, Morse index, 32 boundary modes, the two smallest ', ...
    'singular values of J-I, tangent direction, clamp margins, and population statistics.\n\n']);
fprintf(file,'## Symmetry inventory\n\n');
fprintf(file,'- Candidate transformations tested: %d.\n',height(symmetry));
fprintf(file,'- Verified equation symmetries: %d.\n',sum(symmetry.verifiedEquationSymmetry));
fprintf(file,'- L6 persistent critical sector: (row wave 2, column wave 0).\n');
fprintf(file,'- Inhibition persistent critical sector: (row wave 2, column wave 1).\n');
fprintf(file,'- The verified group and per-root isotropy labels are saved in `symmetry_inventory.mat`.\n\n');
fprintf(file,'## Established local bifurcations\n\n');
fprintf(file,['The persistent L6 and inhibition events remain subcritical pitchforks. ', ...
    'Their established critical weights are -0.173606566 and 0.143763024, ', ...
    'respectively. The sector decomposition independently isolates the unit ', ...
    'eigenvalue in the expected symmetry-breaking representation.\n\n']);
fprintf(file,'## Phase I global atlas\n\n');
fprintf(file,'- Successful continuation task files: %d.\n',height(tasks));
fprintf(file,'- Reconciled connected components: %d.\n',height(components));
fprintf(file,'- Event candidates before local event refinement: %d.\n\n',height(events));
highRateMask=logical(components.containsStableHighRateState);
highRateComponents=components(highRateMask,:);
fprintf(file,'- Components containing stable high-rate states: %d.\n\n',height(highRateComponents));
fprintf(file,'| pathway | components | w range | Morse-index range | minimum sigma_min(J-I) |\n');
fprintf(file,'|---|---:|---:|---:|---:|\n');
for pathway=["L6","Inhibition"]
    subset=components(components.pathway==pathway,:);
    fprintf(file,'| %s | %d | [%.6g, %.6g] | [%d, %d] | %.3e |\n', ...
        pathway,height(subset),min(subset.minimumWeight),max(subset.maximumWeight), ...
        min(subset.minimumUnstableDimension),max(subset.maximumUnstableDimension), ...
        min(subset.minimumSigmaMinA));
end
fprintf(file,'\n## Inhibition near-silent turning region\n\n');
fprintf(file,['Ultrafine continuation localizes a tangent reversal near ', ...
    'w_I=0.27231953, but this is not a smooth saddle-node. At the apparent event, ', ...
    '32 symmetry-related L6 sites simultaneously leave the lower clamp: the raw ', ...
    'L6 value changes from approximately 0.99997 to 1.0002 and the active fraction ', ...
    'changes from 0.82 to 0.80. The analytic Jacobian therefore changes active set, ', ...
    'max Re lambda jumps from about 0.9881 to 1.0019, and the Morse index jumps ', ...
    'from 0 to 2 without a resolved smooth passage through a one-dimensional ', ...
    'kernel. The correct current classification is a symmetry-organized ', ...
    'piecewise-smooth lower-L6-clamp border event. Smooth saddle-node coefficients ', ...
    'eta_SN and b_SN are not valid at this nonsmooth point.\n\n']);
fprintf(file,'## Stable high-rate branches\n\n');
if isempty(highRateComponents)
    fprintf(file,['No sampled component met the documented stable high-rate criterion ', ...
        '(max Re lambda < 1 and either maximum-rate or population-mean ratio >= 2). ', ...
        'This is a negative result only within the continued domain, not proof of absence.\n\n']);
else
    fprintf(file,['The atlas contains %d connected component(s) with at least one ', ...
        'stable high-rate state. High firing rate was recorded as a physical-validity ', ...
        'flag rather than used as a continuation endpoint. The largest stable ', ...
        'rate ratio observed is %.6g and the largest stable firing rate is %.6g.\n\n'], ...
        height(highRateComponents),max(highRateComponents.maximumStableRateRatio), ...
        max(highRateComponents.maximumStableRate));
end
fprintf(file,'## Interpretation and remaining claims\n\n');
fprintf(file,['The atlas establishes connected equilibrium components and their ', ...
    'steady-state stability events within the searched domain. Root and component ', ...
    'counts remain lower bounds until deflated fixed-parameter searches are completed. ', ...
    'Hopf candidates require complex-pair tracking; periodic-orbit continuation and ', ...
    'two-parameter continuation remain Phase II/III work and are not claimed here.\n\n']);
fprintf(file,'## Reproducible artifacts\n\n');
fprintf(file,'- `aggregate/phase1_branch_atlas.mat`: complete reconciled database.\n');
fprintf(file,'- `aggregate/connected_components.tsv`: component summary.\n');
fprintf(file,'- `aggregate/event_candidates.tsv`: tangent and Morse-index events.\n');
fprintf(file,'- `persistent_symmetry_sector_spectra.tsv`: sector-resolved persistent spectra.\n');
fprintf(file,'- `figures/*.pdf` and `figures/*.fig`: report figures.\n');
end
