function build_h96_nn_pages_mex()
% Build double- and single-precision fixed-size h96 predictor MEX kernels.
fastDir = fileparts(mfilename('fullpath'));
oldDir = pwd;
cleanup = onCleanup(@() cd(oldDir));
cd(fastDir);

cfg = coder.config('mex');
cfg.GenerateReport = false;
cfg.EnableOpenMP = true;

build_one(cfg, 'double', 'h96_nn_predict_pages_double_mex');
build_one(cfg, 'single', 'h96_nn_predict_pages_single_mex');
end

function build_one(cfg, precision, outputName)
z = cast(0, precision);
args = { ...
    coder.typeof(z, [8000 1]), ...
    coder.typeof(z, [8000 3]), ...
    coder.typeof(z, [8000 3]), ...
    coder.typeof(z, [8000 5 3]), ...
    coder.typeof(z, [1 5 3]), ...
    coder.typeof(z, [1 5 3]), ...
    coder.typeof(z, [5 96 3]), ...
    coder.typeof(z, [1 96 3]), ...
    coder.typeof(z, [96 96 3]), ...
    coder.typeof(z, [1 96 3]), ...
    coder.typeof(z, [96 96 3]), ...
    coder.typeof(z, [1 96 3]), ...
    coder.typeof(z, [96 1 3]), ...
    coder.typeof(z, [1 1 3]), ...
    coder.typeof(z, [1600 5])};
codegen('-config', cfg, 'h96_nn_predict_pages_codegen', '-args', args, '-o', outputName);
end
