function output = h96_circular_conv3x3(field, kernel)
% Periodic 3-by-3 convolution without padarray allocation or argument parsing.
up = [size(field,1), 1:size(field,1)-1];
down = [2:size(field,1), 1];
left = [size(field,2), 1:size(field,2)-1];
right = [2:size(field,2), 1];
output = kernel(2,2).*field ...
    +kernel(1,2).*field(up,:) + kernel(3,2).*field(down,:) ...
    +kernel(2,1).*field(:,left) + kernel(2,3).*field(:,right) ...
    +kernel(1,1).*field(up,left) + kernel(1,3).*field(up,right) ...
    +kernel(3,1).*field(down,left) + kernel(3,3).*field(down,right);
end
