function aggregate_fpp_offset_comparison()
% Compare real fixed-point, numerical FPP ODE, and theoretical offsets.

outputRoot=getenv('FPP_OFFSET_OUTPUT_ROOT');
theoryFile=getenv('FPP_OFFSET_THEORY_FILE');
realSummaryFile=getenv('FPP_OFFSET_REAL_SUMMARY');
realRegressionFile=getenv('FPP_OFFSET_REAL_REGRESSION');
if isempty(outputRoot) || ~exist(outputRoot,'dir') || ~isfile(theoryFile) || ...
        ~isfile(realSummaryFile) || ~isfile(realRegressionFile)
    error('FppOffset:Environment','Required comparison files are missing.');
end
files=dir(fullfile(outputRoot,'*','case_summary.tsv'));
if isempty(files); error('FppOffset:NoResults','No FPP summaries found.'); end
parts=cell(numel(files),1);
for index=1:numel(files)
    parts{index}=readtable(fullfile(files(index).folder,files(index).name), ...
        'FileType','text','Delimiter','\t','TextType','string');
end
fpp=sortrows(vertcat(parts{:}),'beta6');
writetable(fpp,fullfile(outputRoot,'fpp_offset_summary.tsv'), ...
    'FileType','text','Delimiter','\t');

theory=readtable(theoryFile,'FileType','text','Delimiter','\t');
theorySlope=theory.constantStabilitySlope(1);
realSummary=readtable(realSummaryFile,'FileType','text','Delimiter','\t');
realRegression=readtable(realRegressionFile,'FileType','text','Delimiter','\t', ...
    'TextType','string');
realSlope=realRegression.value(realRegression.metric=="through_origin_slope");
positive=fpp.beta6>0;
x=fpp.beta6(positive); y=fpp.betaI(positive);
fppSlope=dot(x,y)/dot(x,x);
fppResidual=y-fppSlope*x;
fppSlopeSE=sqrt(sum(fppResidual.^2)/max(numel(x)-1,1)/dot(x,x));
fppR2=1-sum(fppResidual.^2)/sum(y.^2);
ordinary=polyfit(x,y,1);
ordinaryPrediction=polyval(ordinary,x);
ordinaryR2=1-sum((y-ordinaryPrediction).^2)/sum((y-mean(y)).^2);
firstSecant=y(1)/x(1);

metrics=table(["real_fixed_point_through_origin"; ...
    "fpp_numeric_constant_stability_through_origin"; ...
    "fpp_numeric_slope_se";"fpp_numeric_r2"; ...
    "fpp_numeric_first_secant";"fpp_ordinary_slope"; ...
    "fpp_ordinary_intercept";"fpp_ordinary_r2"; ...
    "theoretical_infinitesimal_constant_stability"; ...
    "real_relative_difference_from_theory"; ...
    "fpp_relative_difference_from_theory"; ...
    "maximum_fpp_alpha_matching_error"; ...
    "maximum_fpp_fixed_point_residual"; ...
    "maximum_fpp_jvp_relative_error"; ...
    "maximum_ode_decay_rate_error"], ...
    [realSlope;fppSlope;fppSlopeSE;fppR2;firstSecant;ordinary(1); ...
    ordinary(2);ordinaryR2;theorySlope;(realSlope-theorySlope)/theorySlope; ...
    (fppSlope-theorySlope)/theorySlope;max(abs(fpp.matchingError)); ...
    max(fpp.fixedPointResidual);max(fpp.analyticJvpRelativeError); ...
    max(abs(fpp.fittedMinusPredictedDecayPerMs))], ...
    'VariableNames',{'metric','value'});
writetable(metrics,fullfile(outputRoot,'offset_method_comparison.tsv'), ...
    'FileType','text','Delimiter','\t');

figureRoot=fullfile(outputRoot,'figures');
if ~exist(figureRoot,'dir'); mkdir(figureRoot); end
maxBeta=max(fpp.beta6);
lineX=linspace(0,maxBeta,300);
realValid=realSummary.converged & realSummary.HCnorm<0.3;
fig=figure('Visible','off','Color','w','Position',[80 80 1100 760]);
hold on; grid on;
plot(realSummary.beta6(~realValid),realSummary.betaI(~realValid),'x', ...
    'Color',[0.55 0.55 0.55],'LineWidth',1.5,'MarkerSize',7, ...
    'DisplayName','real tuning, HCnorm >= 0.3');
scatter(realSummary.beta6(realValid),realSummary.betaI(realValid),45, ...
    [0.08 0.42 0.72],'filled','DisplayName','real moved fixed point, HCnorm < 0.3');
scatter(fpp.beta6,fpp.betaI,52,[0.85 0.33 0.10],'s','filled', ...
    'DisplayName','FPP ODE, numerical constant stability');
plot(lineX,realSlope*lineX,'-','Color',[0.08 0.42 0.72], ...
    'LineWidth',1.8,'DisplayName',sprintf('real fixed-point slope %.6f',realSlope));
plot(lineX,fppSlope*lineX,'-','Color',[0.85 0.33 0.10], ...
    'LineWidth',2.1,'DisplayName',sprintf('FPP numerical slope %.6f',fppSlope));
plot(lineX,theorySlope*lineX,'k--','LineWidth',1.8, ...
    'DisplayName',sprintf('theoretical local stability slope %.6f',theorySlope));
xlabel('\beta_6 (fractional whole-L6 increase)');
ylabel('\beta_I (fractional whole-inhibition increase)');
title({'Real fixed-point offset versus FPP ODE constant-stability offset', ...
    'The two slopes answer different questions'}, ...
    'Interpreter','none','FontWeight','bold');
legend('Location','northwest','Interpreter','none');
local_save(fig,figureRoot,'03_Real_vs_FPP_vs_Theoretical_Offset');

fig=figure('Visible','off','Color','w','Position',[80 80 1320 580]);
layout=tiledlayout(fig,1,2,'TileSpacing','loose','Padding','compact');
ax=nexttile(layout); semilogy(ax,fpp.beta6,max(fpp.fixedPointResidual,eps), ...
    '-o','LineWidth',1.8,'MarkerSize',5); grid(ax,'on');
xlabel(ax,'\beta_6'); ylabel(ax,'relative FPP map residual at f*');
title(ax,'FPP keeps the baseline fixed point for every pair');
ax=nexttile(layout); plot(ax,fpp.beta6,fpp.fittedDecayPerMs,'-o', ...
    'LineWidth',1.8,'MarkerSize',5); hold(ax,'on'); grid(ax,'on');
yline(ax,fpp.predictedDecayPerMs(1),'k--','LineWidth',1.5, ...
    'DisplayName','baseline leading ODE rate');
xlabel(ax,'\beta_6'); ylabel(ax,'fitted HC decay rate (ms^{-1})');
title(ax,'Nonlinear FPP ODE decay after numerical compensation');
legend(ax,'numerical ODE fit','baseline leading ODE rate', ...
    'Location','southwest','Interpreter','none');
title(layout,'FPP fixed-point degeneracy and ODE-rate validation', ...
    'FontWeight','bold');
local_save(fig,figureRoot,'04_FPP_Fixed_Point_and_ODE_Rate_Validation');

traceFiles=dir(fullfile(outputRoot,'*','ode_trace*.tsv'));
traces=cell(numel(traceFiles),1);
for index=1:numel(traceFiles)
    traces{index}=readtable(fullfile(traceFiles(index).folder,traceFiles(index).name), ...
        'FileType','text','Delimiter','\t','TextType','string');
end
allTraces=vertcat(traces{:});
writetable(allTraces,fullfile(outputRoot,'all_fpp_ode_traces.tsv'), ...
    'FileType','text','Delimiter','\t');
base=allTraces(allTraces.kind=="matched" & abs(allTraces.beta6)<1e-12,:);
representativeBeta=max(fpp.beta6);
matched=allTraces(allTraces.kind=="matched" & ...
    abs(allTraces.beta6-representativeBeta)<1e-12,:);
l6Only=allTraces(allTraces.kind=="l6_only" & ...
    abs(allTraces.beta6-representativeBeta)<1e-12,:);
if isempty(base) || isempty(matched) || isempty(l6Only)
    error('FppOffset:Traces','Baseline, matched, or L6-only ODE trace is missing.');
end
fig=figure('Visible','off','Color','w','Position',[80 80 1250 560]);
layout=tiledlayout(fig,1,2,'TileSpacing','compact','Padding','compact');
ax=nexttile(layout); semilogy(ax,base.timeMs,base.HCnorm,'k-', ...
    'LineWidth',2,'DisplayName','baseline'); hold(ax,'on');
semilogy(ax,l6Only.timeMs,l6Only.HCnorm,'--','Color',[0.55 0.25 0.70], ...
    'LineWidth',1.8,'DisplayName',sprintf('FPP L6-only beta6=%.3f',representativeBeta));
semilogy(ax,matched.timeMs,matched.HCnorm,'-','Color',[0.85 0.33 0.10], ...
    'LineWidth',1.8,'DisplayName',sprintf('FPP compensated betaI=%.5f',matched.betaI(1)));
grid(ax,'on'); xlabel(ax,'time (ms)'); ylabel(ax,'HCnorm from f*');
title(ax,'Same small perturbation under the nonlinear FPP ODE');
legend(ax,'Location','southwest','Interpreter','none');
ax=nexttile(layout);
plot(ax,matched.timeMs,matched.HCnorm./base.HCnorm,'-','Color',[0.85 0.33 0.10], ...
    'LineWidth',1.8,'DisplayName','compensated / baseline'); hold(ax,'on');
plot(ax,l6Only.timeMs,l6Only.HCnorm./base.HCnorm,'--','Color',[0.55 0.25 0.70], ...
    'LineWidth',1.8,'DisplayName','L6-only / baseline');
yline(ax,1,'k:','LineWidth',1.3,'HandleVisibility','off'); grid(ax,'on');
xlabel(ax,'time (ms)'); ylabel(ax,'HCnorm ratio');
title(ax,'Compensation matches the asymptotic rate, not the full trajectory');
legend(ax,'Location','northwest','Interpreter','none');
title(layout,sprintf(['FPP ODE trajectory check: beta6 %.3f, betaI %.5f, ' ...
    'theory ratio %.6f'],representativeBeta,matched.betaI(1),theorySlope), ...
    'Interpreter','none','FontWeight','bold');
local_save(fig,figureRoot,'05_FPP_ODE_Compensated_Trajectory');

save(fullfile(outputRoot,'fpp_offset_comparison.mat'),'fpp','realSummary', ...
    'metrics','theory','allTraces','fppSlope','fppSlopeSE','fppR2', ...
    'ordinary','ordinaryR2','realSlope','theorySlope','-v7.3');
fprintf(['FPP comparison: real slope %.8f, FPP numerical %.8f, ' ...
    'theoretical %.8f; max residual %.3e.\n'],realSlope,fppSlope, ...
    theorySlope,max(fpp.fixedPointResidual));
end

function local_save(fig,root,stem)
savefig(fig,fullfile(root,[stem '.fig']));
exportgraphics(fig,fullfile(root,[stem '.pdf']),'ContentType','vector');
close(fig);
end
