function approximation = audit_fpp_second_order_approximation(setupFile, outputRoot)
% Compute quadratic constant-leading-eigenvalue paths for all pathway pairs.

if nargin < 1 || isempty(setupFile)
    codeRoot = fileparts(mfilename('fullpath'));
    setupFile = fullfile(codeRoot, 'results_global_bifurcation_20260722', ...
        'global_bifurcation_setup.mat');
end
if nargin < 2 || isempty(outputRoot)
    outputRoot = fullfile( ...
        '/Users/xialeihuang/Desktop/Neuroscience_Project/Spectral_Analysis', ...
        'matlab-inserting_into_CG_model/Complete_Code_for_Paper3', ...
        'NYU-Vision-2Drive-main/Figures/spectral_analysis_eigenvalue_eigenvectors', ...
        'L6 and Inhibition');
end

loaded = load(setupFile, 'setup');
cfg = loaded.setup.Config;
pathway = loaded.setup.Pathway;
jBaseline = pathway.JBaseline;
components = {pathway.J6, pathway.JRest, pathway.JI};
componentNames = {'L6','Excitation','Inhibition'};

[alpha0, leadingValues] = local_max_real(jBaseline, cfg);
sortedReal = sort(real(leadingValues), 'descend');
spectralGap = sortedReal(1)-sortedReal(2);
hessianStep = 1e-3;
hessian = zeros(3);
for first = 1:3
    plus = local_max_real(jBaseline+hessianStep*components{first}, cfg);
    minus = local_max_real(jBaseline-hessianStep*components{first}, cfg);
    hessian(first,first) = (plus-2*alpha0+minus)/(hessianStep^2);
    for second = first+1:3
        plusPlus = local_max_real(jBaseline + ...
            hessianStep*components{first} + hessianStep*components{second}, cfg);
        plusMinus = local_max_real(jBaseline + ...
            hessianStep*components{first} - hessianStep*components{second}, cfg);
        minusPlus = local_max_real(jBaseline - ...
            hessianStep*components{first} + hessianStep*components{second}, cfg);
        minusMinus = local_max_real(jBaseline - ...
            hessianStep*components{first} - hessianStep*components{second}, cfg);
        value = (plusPlus-plusMinus-minusPlus+minusMinus)/(4*hessianStep^2);
        hessian(first,second) = value;
        hessian(second,first) = value;
    end
end

firstOrder = audit_fpp_theoretical_slopes(setupFile, outputRoot);
sensitivities = [firstOrder.SensitivityL6; ...
    firstOrder.SensitivityExcitation; firstOrder.SensitivityInhibition];
pairs = [1 3; 1 2; 2 3];
pairNames = ["L6_Inhibition"; "L6_Excitation"; "Excitation_Inhibition"];
firstSlope = zeros(3,1);
secondCoefficient = zeros(3,1);
testBetaX = repmat(0.01,3,1);
firstOrderAlphaError = zeros(3,1);
secondOrderAlphaError = zeros(3,1);
for pairIndex = 1:3
    xIndex = pairs(pairIndex,1);
    yIndex = pairs(pairIndex,2);
    sx = sensitivities(xIndex);
    sy = sensitivities(yIndex);
    hxx = hessian(xIndex,xIndex);
    hxy = hessian(xIndex,yIndex);
    hyy = hessian(yIndex,yIndex);
    firstSlope(pairIndex) = -sx/sy;
    secondCoefficient(pairIndex) = -(hxx + ...
        2*hxy*firstSlope(pairIndex) + ...
        hyy*firstSlope(pairIndex)^2)/(2*sy);
    x = testBetaX(pairIndex);
    yFirst = firstSlope(pairIndex)*x;
    ySecond = yFirst+secondCoefficient(pairIndex)*x^2;
    jFirst = jBaseline+x*components{xIndex}+yFirst*components{yIndex};
    jSecond = jBaseline+x*components{xIndex}+ySecond*components{yIndex};
    firstOrderAlphaError(pairIndex) = local_max_real(jFirst,cfg)-alpha0;
    secondOrderAlphaError(pairIndex) = local_max_real(jSecond,cfg)-alpha0;
end

pairTable = table(pairNames,componentNames(pairs(:,1))', ...
    componentNames(pairs(:,2))',firstSlope,secondCoefficient,testBetaX, ...
    firstOrderAlphaError,secondOrderAlphaError, ...
    abs(secondOrderAlphaError)./max(abs(firstOrderAlphaError),eps), ...
    'VariableNames', {'pair','xPathway','yPathway','firstOrderSlope', ...
    'secondOrderCoefficient','validationBetaX','firstOrderAlphaError', ...
    'secondOrderAlphaError','secondToFirstAbsoluteErrorRatio'});
hessianTable = array2table(hessian, 'VariableNames', ...
    {'beta6','betaE','betaI'}, 'RowNames', {'beta6','betaE','betaI'});
summary = table(alpha0,spectralGap,hessianStep,max(abs(hessian-hessian'),[],'all'), ...
    'VariableNames', {'baselineLeadingReal','baselineTopRealSpectralGap', ...
    'hessianFiniteDifferenceStep','hessianSymmetryAbsoluteError'});

writetable(pairTable, fullfile(outputRoot, ...
    'theoretical_fpp_second_order_paths.tsv'), ...
    'FileType', 'text', 'Delimiter', '\t');
writetable(hessianTable, fullfile(outputRoot, ...
    'theoretical_fpp_eigenvalue_hessian.tsv'), ...
    'FileType', 'text', 'Delimiter', '\t', 'WriteRowNames', true);
writetable(summary, fullfile(outputRoot, ...
    'theoretical_fpp_second_order_summary.tsv'), ...
    'FileType', 'text', 'Delimiter', '\t');

approximation = struct('PairTable',pairTable,'Hessian',hessian, ...
    'Summary',summary,'Sensitivity',sensitivities, ...
    'L6InhibitionFirst',firstSlope(1), ...
    'L6InhibitionSecond',secondCoefficient(1), ...
    'L6ExcitationFirst',firstSlope(2), ...
    'L6ExcitationSecond',secondCoefficient(2), ...
    'ExcitationInhibitionFirst',firstSlope(3), ...
    'ExcitationInhibitionSecond',secondCoefficient(3));
save(fullfile(outputRoot, 'theoretical_fpp_second_order_audit.mat'), ...
    'approximation','pairTable','hessian','summary','-v7.3');
fprintf(['Second-order coefficients: L6-I %+.9g, L6-E %+.9g, ' ...
    'E-I %+.9g.\n'], secondCoefficient(1), secondCoefficient(2), ...
    secondCoefficient(3));
end

function [alpha, values] = local_max_real(matrix, cfg)
count = 6;
options = struct('tol',cfg.EigsTolerance,'maxit',cfg.EigsMaxIterations, ...
    'p',min(max(cfg.EigsSubspaceDimension,2*count+8),size(matrix,1)), ...
    'disp',0,'isreal',true, ...
    'v0',ones(size(matrix,1),1)/sqrt(size(matrix,1)));
try
    [~, valueMatrix] = eigs(matrix,count,'largestreal',options);
catch
    [~, valueMatrix] = eigs(matrix,count,'lr',options);
end
values = diag(valueMatrix);
alpha = max(real(values));
end
