function output = run_spatial_smoothing_rank_control_task(taskIndex,setupFile,outputRoot)
% Test spatial effective rank while preserving symmetry and block row sums.

if nargin < 1 || isempty(taskIndex)
    taskIndex = str2double(getenv('SLURM_ARRAY_TASK_ID'));
end
if nargin < 2 || isempty(setupFile)
    setupFile = getenv('SPATIAL_CONTROL_SETUP');
end
if nargin < 3 || isempty(outputRoot)
    outputRoot = getenv('SPATIAL_CONTROL_OUTPUT');
end
if ~exist(outputRoot,'dir'); mkdir(outputRoot); end

controls = table( ...
    [0;0;1;1;0.25;0.50;0.75], ...
    [0;1;0;1;0.25;0.50;0.75], ...
    ["baseline";"L6_delta";"L4_delta";"L4_L6_delta"; ...
     "joint_alpha_0p25";"joint_alpha_0p50";"joint_alpha_0p75"], ...
    'VariableNames',{'l4Alpha','l6Alpha','name'});
if taskIndex<1 || taskIndex>height(controls)
    error('SpatialControl:Task','Task index must be 1--%d.',height(controls));
end

loaded = load(setupFile,'setup');
setup = loaded.setup;
control = controls(taskIndex,:);
J = l6ns_spatial_smoothing_control_jacobian(setup, ...
    control.l4Alpha,control.l6Alpha);
if taskIndex==1
    relativeBaselineError = norm(J-setup.Pathway.JBaseline,'fro')/ ...
        max(norm(setup.Pathway.JBaseline,'fro'),eps);
    if relativeBaselineError>1e-10
        error('SpatialControl:Baseline','Baseline reconstruction error %.3e.', ...
            relativeBaselineError);
    end
else
    relativeBaselineError = norm(J-setup.Pathway.JBaseline,'fro')/ ...
        max(norm(setup.Pathway.JBaseline,'fro'),eps);
end

denseJ = full(J);
eigenvalues = eig(denseJ,'vector');
singularValues = svd(denseJ);
frobeniusNorm = norm(singularValues);
stableRank = frobeniusNorm^2/singularValues(1)^2;
energy = singularValues.^2/frobeniusNorm^2;
entropyEffectiveRank = exp(-sum(energy.*log(max(energy,realmin))));

summary = table(control.name,control.l4Alpha,control.l6Alpha, ...
    relativeBaselineError,max(real(eigenvalues)),min(real(eigenvalues)), ...
    sum(abs(eigenvalues)<=0.01),sum(abs(eigenvalues)<=0.025), ...
    sum(abs(eigenvalues)<=0.05),sum(singularValues<=0.01), ...
    sum(singularValues<=0.025),sum(singularValues<=0.05), ...
    singularValues(1),singularValues(end),stableRank,entropyEffectiveRank, ...
    'VariableNames',{'control','l4Alpha','l6Alpha', ...
    'relativeBaselineChange','maximumRealEigenvalue','minimumRealEigenvalue', ...
    'countAbsEigLE0p01','countAbsEigLE0p025','countAbsEigLE0p05', ...
    'countSingularLE0p01','countSingularLE0p025','countSingularLE0p05', ...
    'largestSingularValue','smallestSingularValue','stableRank', ...
    'entropyEffectiveRank'});

tag = char(control.name);
writetable(summary,fullfile(outputRoot,['summary_' tag '.tsv']), ...
    'FileType','text','Delimiter','\t');
save(fullfile(outputRoot,['spectrum_' tag '.mat']), ...
    'summary','eigenvalues','singularValues','-v7.3');
output = struct('Summary',summary,'Eigenvalues',eigenvalues, ...
    'SingularValues',singularValues);
fprintf('%s: Nlambda=.05 %d, Nsigma=.05 %d, stable rank %.3f\n', ...
    tag,summary.countAbsEigLE0p05,summary.countSingularLE0p05,stableRank);
end
