function run_raw_extension_test()
% Test whether the high-rate fixed point exists for the raw h96 NN map.

paths = mechanism_initialize();
loaded = load(paths.SetupFile,'setup');
context = loaded.setup.Context;
baseline = context.FixedPoint(:);
summary = readtable(fullfile(paths.ResultsRoot,'all_case_summary.tsv'), ...
    'FileType','text','Delimiter','\t','TextType','string');
pathways = ["L6";"Inhibition"];
betas = [.30;-.10];
rows = cell(numel(betas),1);

for index = 1:numel(betas)
    pathway = pathways(index);
    beta = betas(index);
    highState = local_saved_state(paths.ResultsRoot,summary,pathway,beta);
    gain6 = 1;
    gainI = 1;
    if pathway=="L6"; gain6 = 1+beta; else; gainI = 1+beta; end
    phiExtended = @(x)mechanism_phi_variant(x,context,gain6,gainI,'extended');
    phiRaw = @(x)mechanism_phi_variant(x,context,gain6,gainI,'raw');
    extendedResidualAtHigh = norm(phiExtended(highState)-highState)/norm(highState);
    rawResidualAtHigh = norm(phiRaw(highState)-highState)/norm(highState);
    rawFromBaseline = real_tuning_fixed_point(phiRaw,baseline,context.RelaxationP);
    rawFromHigh = real_tuning_fixed_point(phiRaw,highState,context.RelaxationP);
    rows{index} = table(pathway,beta,extendedResidualAtHigh,rawResidualAtHigh, ...
        rawFromBaseline.Converged,string(rawFromBaseline.Termination), ...
        rawFromBaseline.Iterations,rawFromBaseline.Residual, ...
        rawFromBaseline.MinimumRateHz,rawFromBaseline.MaximumRateHz, ...
        rawFromHigh.Converged,string(rawFromHigh.Termination), ...
        rawFromHigh.Iterations,rawFromHigh.Residual, ...
        rawFromHigh.MinimumRateHz,rawFromHigh.MaximumRateHz, ...
        'VariableNames',{'pathway','beta','extendedResidualAtExtendedHighState', ...
        'rawResidualAtExtendedHighState','rawFromBaselineConverged', ...
        'rawFromBaselineTermination','rawFromBaselineIterations', ...
        'rawFromBaselineResidual','rawFromBaselineMinimumRateHz', ...
        'rawFromBaselineMaximumRateHz','rawFromHighConverged', ...
        'rawFromHighTermination','rawFromHighIterations','rawFromHighResidual', ...
        'rawFromHighMinimumRateHz','rawFromHighMaximumRateHz'});
    fprintf(['%s beta=%+.3f: residual at high extended/raw %.3e / %.3e; ' ...
        'raw from baseline converged=%d max=%.3f; raw from high converged=%d max=%.3f\n'], ...
        pathway,beta,extendedResidualAtHigh,rawResidualAtHigh, ...
        rawFromBaseline.Converged,rawFromBaseline.MaximumRateHz, ...
        rawFromHigh.Converged,rawFromHigh.MaximumRateHz);
end

rawExtensionTable = vertcat(rows{:});
writetable(rawExtensionTable,fullfile(paths.OutputRoot,'raw_extension_test.tsv'), ...
    'FileType','text','Delimiter','\t');
save(fullfile(paths.OutputRoot,'raw_extension_test.mat'),'rawExtensionTable','-v7.3');
end

function state = local_saved_state(resultsRoot,summary,pathway,beta)
mask = summary.pathway==pathway & abs(summary.beta-beta)<1e-10;
taskId = summary.taskId(mask);
match = dir(fullfile(resultsRoot,sprintf('%03d_*',taskId),'case_result.mat'));
loaded = load(fullfile(match.folder,match.name),'moved');
state = loaded.moved(:);
end
