function run_figure1g_snn3_trial(repoRoot,bundleFile,resultsRoot,repeatIndex)
% Time one full Paper 2 3x3 SNN run without trace or figure bookkeeping.
addpath(fullfile(repoRoot,'Utils'));
repeatIndex = str2double(string(repeatIndex));
assert(isfinite(repeatIndex) && repeatIndex >= 1 && repeatIndex == floor(repeatIndex));
cpus = str2double(getenv('SLURM_CPUS_PER_TASK'));
if ~isfinite(cpus), cpus = 1; end
maxNumCompThreads(cpus);
B = load(bundleFile);
assert(B.N_HC == 3 && B.T == 10000 && B.dt == 0.1);
rng(20260901 + repeatIndex,'twister');

RefTimeE=B.InEs.RefTimeE; VE=B.InEs.VE; SpE=B.InEs.SpE;
GE_ampa_R=B.InEs.GE_ampa_R; GE_nmda_R=B.InEs.GE_nmda_R; GE_gaba_R=B.InEs.GE_gaba_R;
GE_ampa_D=B.InEs.GE_ampa_D; GE_nmda_D=B.InEs.GE_nmda_D; GE_gaba_D=B.InEs.GE_gaba_D;
RefTimeI=B.InIs.RefTimeI; VI=B.InIs.VI; SpI=B.InIs.SpI;
GI_ampa_R=B.InIs.GI_ampa_R; GI_nmda_R=B.InIs.GI_nmda_R; GI_gaba_R=B.InIs.GI_gaba_R;
GI_ampa_D=B.InIs.GI_ampa_D; GI_nmda_D=B.InIs.GI_nmda_D; GI_gaba_D=B.InIs.GI_gaba_D;
N_EEDly=floor(0.1/B.dt); N_IEDly=floor(0.1/B.dt); N_EIDly=floor(0.1/B.dt);
EEDlyRcd=sparse(B.N_E,N_EEDly);
IEDlyRcd=ones(B.N_I,N_IEDly);
EIDlyRcd=ones(B.N_E,N_EIDly);

timer=tic;
PhaseE=single(B.tMod*rand(B.N_E,1));
lgnE_Events=PoissonInputForNetwork(B.N_E,B.lambda_E_drive_Pre*(1-B.LGNCurInp),B.T*B.TimeFrac,B.dt);
lgnI_Events=PoissonInputForNetwork(B.N_I,B.lambda_I_drive_Pre*(1-B.LGNCurInp),B.T*B.TimeFrac,B.dt);
AmbE_Events=PoissonInputForNetwork(B.N_E,B.rE_amb,B.T*B.TimeFrac,B.dt);
AmbI_Events=PoissonInputForNetwork(B.N_I,B.rI_amb,B.T*B.TimeFrac,B.dt);
L6E_Events=PoissonInputForNetwork(B.N_E,B.rE_L6_Drive*(1-B.L6CurInp),B.T*B.TimeFrac,B.dt);
L6I_Events=PoissonInputForNetwork(B.N_I,B.rI_L6_Drive*(1-B.L6CurInp),B.T*B.TimeFrac,B.dt);
MaxInpBin=floor(B.T*B.TimeFrac/B.dt);
stepsPerPart=floor(B.T/B.dt/B.TPar);

for TSec=1:B.TPar %#ok<NASGU>
    for TimeN=1:stepsPerPart
        PhaseE=mod(PhaseE+B.dt,B.tMod);
        InpWin=100;
        FrameNum=floor(InpWin/B.dt);
        FrameInd=mod(TimeN,FrameNum);
        if FrameInd==0, FrameInd=FrameNum; end
        RandTimBin=randi([1 MaxInpBin+1],6,FrameNum);
        if FrameInd==1
            tt=0:B.dt:InpWin-B.dt;
            PhaseAll=floor(mod(PhaseE+tt,B.tMod)/B.MaxOnPhase)*B.N_E + ...
                repmat((1:B.N_E)',1,numel(tt));
            AdjlgnE=B.LGNE_Drive(PhaseAll);
            EampaInp=single(full(B.S_Elgn*(lgnE_Events(:,RandTimBin(1,:)).* ...
                AdjlgnE/B.lambda_E_drive_Pre + AdjlgnE*B.dt*B.LGNCurInp) + ...
                B.S_amb*AmbE_Events(:,RandTimBin(3,:)) + ...
                B.S_EL6*(L6E_Events(:,RandTimBin(5,:)) + ...
                B.rE_L6_Drive*B.dt*B.L6CurInp)*B.rhoE_ampa));
            IampaInp=single(full(B.S_Ilgn*(lgnI_Events(:,RandTimBin(2,:)) + ...
                B.lambda_I_drive_Pre*B.dt*B.LGNCurInp) + ...
                B.S_amb*AmbI_Events(:,RandTimBin(4,:)) + ...
                B.S_IL6*(L6I_Events(:,RandTimBin(6,:)) + ...
                B.rI_L6_Drive*B.dt*B.L6CurInp)*B.rhoI_ampa));
            EnmdaInp=single(full(B.S_EL6*(L6E_Events(:,RandTimBin(5,:)) + ...
                B.rE_L6_Drive*B.dt*B.L6CurInp)*B.rhoE_nmda));
            InmdaInp=single(full(B.S_IL6*(L6I_Events(:,RandTimBin(6,:)) + ...
                B.rI_L6_Drive*B.dt*B.L6CurInp)*B.rhoI_nmda));
        end
        [RefTimeE,VE,SpE,GE_ampa_R,GE_nmda_R,GE_gaba_R, ...
            GE_ampa_D,GE_nmda_D,GE_gaba_D,RefTimeI,VI,SpI, ...
            GI_ampa_R,GI_nmda_R,GI_gaba_R,GI_ampa_D,GI_nmda_D,GI_gaba_D, ...
            EEDlyRcd,IEDlyRcd,EIDlyRcd] = ...
            V1NetworkUpdate_Ver3_Drive_PoissonRead_EEnIEnEIDelay( ...
            RefTimeE,VE,SpE,GE_ampa_R,GE_nmda_R,GE_gaba_R, ...
            GE_ampa_D,GE_nmda_D,GE_gaba_D,RefTimeI,VI,SpI, ...
            GI_ampa_R,GI_nmda_R,GI_gaba_R,GI_ampa_D,GI_nmda_D,GI_gaba_D, ...
            EEDlyRcd,IEDlyRcd,EIDlyRcd,B.C_EE_Fix_Bd,B.C_EI_Fix_Bd, ...
            B.C_IE_Fix_Bd,B.C_II_Fix_Bd,B.S_EE,B.S_EI,B.S_IE,B.S_II, ...
            B.tau_ampa_R,B.tau_ampa_D,B.tau_nmda_R,B.tau_nmda_D, ...
            B.tau_gaba_R,B.tau_gaba_D,B.tau_ref,B.dt,B.p_EEFail, ...
            B.gL_E,B.Ve,B.rhoE_ampa,B.rhoE_nmda,B.gL_I,B.Vi, ...
            B.rhoI_ampa,B.rhoI_nmda,EampaInp(:,FrameInd),IampaInp(:,FrameInd), ...
            EnmdaInp(:,FrameInd),InmdaInp(:,FrameInd));
    end
end
seconds=toc(timer);
steps=B.T/B.dt;
checksum=sum(double(VE),'omitnan')+sum(double(VI),'omitnan')+nnz(SpE)+nnz(SpI);
T=table(3,repeatIndex,"SNN",seconds,B.T,B.dt,steps,cpus,checksum, ...
    'VariableNames',{'FieldHC','Repeat','Method','Seconds','SimulatedMs', ...
    'DtMs','Steps','CPUs','Checksum'});
if ~exist(resultsRoot,'dir'), mkdir(resultsRoot); end
outFile=fullfile(resultsRoot,sprintf('snn_real_03HC_repeat_%03d.tsv',repeatIndex));
writetable(T,outFile,'FileType','text','Delimiter','\t');
fprintf('SNN field=3 repeat=%d seconds=%.6f steps=%d checksum=%.9g\n', ...
    repeatIndex,seconds,steps,checksum);
end
