function [dPhi_dL4E, dPhi_dL4I, dPhi_dL6] = ...
    local_h96baseline_pref6D_grads_momentcorrected( ...
    celltype, L4EUse, L4IUse, L6Use, ContrastUse, OrientationUse, PixLGNCtgr, Perturb)
% Differentiate the corrected local response without changing base NN gains.

[dPhi_dL4E, dPhi_dL4I, dPhi_dL6] = local_h96baseline_pref6D_grads( ...
    celltype, L4EUse, L4IUse, L6Use, ContrastUse, OrientationUse, PixLGNCtgr);

if ~getfield_default(Perturb, 'MomentCorrection', false)
    return;
end

steps = getfield_default(Perturb, 'MomentGradientSteps', ...
    0.001 * [13150.58496, 7195.099609, 11.16841793]);
if numel(steps) ~= 3 || any(~isfinite(steps)) || any(steps <= 0)
    error('local_h96baseline_pref6D_grads_momentcorrected:InvalidSteps', ...
        'MomentGradientSteps must contain three positive finite values.');
end

plus = h96_pref6D_strength_moment_correction( ...
    celltype, L4EUse + steps(1), L4IUse, L6Use, ...
    ContrastUse, OrientationUse, PixLGNCtgr, Perturb);
minus = h96_pref6D_strength_moment_correction( ...
    celltype, L4EUse - steps(1), L4IUse, L6Use, ...
    ContrastUse, OrientationUse, PixLGNCtgr, Perturb);
dPhi_dL4E = dPhi_dL4E + (plus - minus) / (2 * steps(1));

plus = h96_pref6D_strength_moment_correction( ...
    celltype, L4EUse, L4IUse + steps(2), L6Use, ...
    ContrastUse, OrientationUse, PixLGNCtgr, Perturb);
minus = h96_pref6D_strength_moment_correction( ...
    celltype, L4EUse, L4IUse - steps(2), L6Use, ...
    ContrastUse, OrientationUse, PixLGNCtgr, Perturb);
dPhi_dL4I = dPhi_dL4I + (plus - minus) / (2 * steps(2));

plus = h96_pref6D_strength_moment_correction( ...
    celltype, L4EUse, L4IUse, L6Use + steps(3), ...
    ContrastUse, OrientationUse, PixLGNCtgr, Perturb);
minus = h96_pref6D_strength_moment_correction( ...
    celltype, L4EUse, L4IUse, L6Use - steps(3), ...
    ContrastUse, OrientationUse, PixLGNCtgr, Perturb);
dPhi_dL6 = dPhi_dL6 + (plus - minus) / (2 * steps(3));
end

function val = getfield_default(s, name, defaultVal)
if isstruct(s) && isfield(s, name) && ~isempty(s.(name))
    val = s.(name);
else
    val = defaultVal;
end
end
