function replot_all_perturbation_figures_with_finite_time(runRoot,finiteTimeRoot,outputRoot,denseCurveRoot)
% Regenerate report Figures 7.1-7.12 with a finite-time transient column.

setupLoaded = load(fullfile(runRoot,'code','global_bifurcation_setup.mat'),'setup');
setup = setupLoaded.setup;
context = setup.Context;
fixed = context.FixedPoint(:);
n = prod(double(context.MapSize(:).'));
jBaseline = l6ns_state_jacobian(setup,'L6',fixed,0);
[baselineOutput,~,baselineInput] = svds(jBaseline,1,'largest');
if real(baselineOutput'*baselineInput)<0
    baselineOutput = -baselineOutput;
end
baselineSingularOutputEMap = reshape( ...
    (1-context.CWeight)*real(baselineOutput(1:n))+ ...
    context.CWeight*real(baselineOutput(n+(1:n))), ...
    double(context.MapSize(:).'));

figureNumbers = {'7.1','7.2','7.3','7.4','7.5','7.6', ...
    '7.7','7.8','7.9','7.10','7.11','7.12'};
sourceRelativePaths = { ...
    'outputs/7.1_Perturbation_Transient_and_Return_Baseline_L6_data.mat', ...
    'outputs/7.2_Perturbation_Transient_and_Return_Enhanced_L6_1p15x_data.mat', ...
    'outputs/7.4_Perturbation_Transient_and_Return_Baseline_L6_LargePerturbation_HC0p30_data.mat', ...
    'outputs/7.5_Perturbation_Transient_and_Return_Baseline_L6_RandomPositive_HC1_data.mat', ...
    'outputs/7.6_Perturbation_Transient_and_Return_Baseline_L6_RandomPositive_HC5_data.mat', ...
    'fixed_point_row_figures/7.6_Perturbation_Transient_and_Return_Baseline_L6_FixedDirection_HC6p00_fixedpointrow_data.mat', ...
    'fixed_point_row_figures/7.7_Perturbation_Transient_and_Return_Baseline_L6_FixedDirection_HC6p01_fixedpointrow_data.mat', ...
    'fixed_point_row_figures/7.8_Perturbation_Transient_and_Return_Baseline_L6_FixedDirection_HC6p02_fixedpointrow_data.mat', ...
    'fixed_direction_boundary_figures/7.9_Perturbation_Transient_and_Return_Baseline_L6_FixedDirection_HC6p03_data.mat', ...
    'fixed_direction_boundary_figures/7.10_Perturbation_Transient_and_Return_Baseline_L6_FixedDirection_HC6p10_data.mat', ...
    'fixed_direction_boundary_figures/7.11_Perturbation_Transient_and_Return_Baseline_L6_FixedDirection_HC6p50_data.mat', ...
    'outputs/7.7_Perturbation_Transient_and_Return_Baseline_L6_RandomPositive_HC10_data.mat'};
outputNames = { ...
    '7.1_Perturbation_Transient_and_Return_Baseline_L6.pdf', ...
    '7.2_Perturbation_Transient_and_Return_Enhanced_L6_1p15x.pdf', ...
    '7.3_Perturbation_Transient_and_Return_Baseline_L6_LargePerturbation_HC0p30.pdf', ...
    '7.4_Perturbation_Transient_and_Return_Baseline_L6_RandomPositive_HC1.pdf', ...
    '7.5_Perturbation_Transient_and_Return_Baseline_L6_RandomPositive_HC5.pdf', ...
    '7.6_Perturbation_Transient_and_Return_Baseline_L6_FixedDirection_HC6p00.pdf', ...
    '7.7_Perturbation_Transient_and_Return_Baseline_L6_FixedDirection_HC6p01.pdf', ...
    '7.8_Perturbation_Transient_and_Return_Baseline_L6_FixedDirection_HC6p02.pdf', ...
    '7.9_Perturbation_Transient_and_Return_Baseline_L6_FixedDirection_HC6p03.pdf', ...
    '7.10_Perturbation_Transient_and_Return_Baseline_L6_FixedDirection_HC6p10.pdf', ...
    '7.11_Perturbation_Transient_and_Return_Baseline_L6_FixedDirection_HC6p50.pdf', ...
    '7.12_Perturbation_Transient_and_Return_Baseline_L6_RandomPositive_HC10.pdf'};

if ~exist(outputRoot,'dir')
    mkdir(outputRoot);
end
for index = 1:numel(figureNumbers)
    fprintf('Plotting %s (%d/%d).\n', ...
        figureNumbers{index},index,numel(figureNumbers));
    replot_perturbation_e_with_finite_time( ...
        fullfile(runRoot,sourceRelativePaths{index}),finiteTimeRoot, ...
        fullfile(outputRoot,outputNames{index}),figureNumbers{index}, ...
        baselineSingularOutputEMap,denseCurveRoot);
end
end
