function replot_existing_perturbation_figures(dataRoot,outputRoot)
% Replot historical perturbation pages with their final report numbers.

arguments
    dataRoot (1,:) char
    outputRoot (1,:) char
end

if ~exist(outputRoot,'dir')
    mkdir(outputRoot);
end
sourceNames = { ...
    '7.4_Perturbation_Transient_and_Return_Baseline_L6_LargePerturbation_HC0p30_data.mat'; ...
    '7.5_Perturbation_Transient_and_Return_Baseline_L6_RandomPositive_HC1_data.mat'; ...
    '7.6_Perturbation_Transient_and_Return_Baseline_L6_RandomPositive_HC5_data.mat'; ...
    '7.7_Perturbation_Transient_and_Return_Baseline_L6_RandomPositive_HC10_data.mat'};
outputNames = { ...
    '7.3_Perturbation_Transient_and_Return_Baseline_L6_LargePerturbation_HC0p30.pdf'; ...
    '7.4_Perturbation_Transient_and_Return_Baseline_L6_RandomPositive_HC1.pdf'; ...
    '7.5_Perturbation_Transient_and_Return_Baseline_L6_RandomPositive_HC5.pdf'; ...
    '7.12_Perturbation_Transient_and_Return_Baseline_L6_RandomPositive_HC10.pdf'};
figureNumbers = {'7.3';'7.4';'7.5';'7.12'};
for index = 1:numel(sourceNames)
    replot_perturbation_e_only(fullfile(dataRoot,sourceNames{index}), ...
        fullfile(outputRoot,outputNames{index}),figureNumbers{index});
end
end
