function make_Final_Figures_2D_2E
% Rebuild the two pathway panels from the original full beta-sweep table.

dataFile = ['/Users/xialeihuang/Desktop/Neuroscience_Project/Spectral_Analysis/' ...
    'matlab-inserting_into_CG_model/l6_next_stage_analysis_20260717/' ...
    'real_tuning_l6_i_20260722/results_full_20260722_055032/' ...
    'all_case_summary.tsv'];
outputRoot = ['/Users/xialeihuang/Desktop/Neuroscience_Project/' ...
    'Spectral_Analysis_Report/Figures'];

summary = readtable(dataFile, 'FileType', 'text', ...
    'Delimiter', '\t', 'TextType', 'string');

neuroColors = [
    178  24  43
    227  74  51
    254 227 145
    171 217 233
     67 147 195
     33 102 172
] / 255;

make_one_panel(summary, "L6", "L6 pathway", ...
    fullfile(tempdir, 'Figure_2D_editable_source.pdf'), ...
    fullfile(outputRoot, 'Final draft', 'Figure 2D.fig'), 'northwest', ...
    neuroColors(6, :), neuroColors(1, :));
make_one_panel(summary, "Inhibition", "Inhibition pathway", ...
    fullfile(tempdir, 'Figure_2E_editable_source.pdf'), ...
    fullfile(outputRoot, 'Final draft', 'Figure 2E.fig'), 'northeast', ...
    neuroColors(6, :), neuroColors(1, :));
end

function make_one_panel(summary, pathway, panelTitle, outputPdf, outputFig, ...
    legendLocation, movedColor, fppColor)

one = sortrows(summary(summary.pathway == pathway, :), 'beta');

fig = figure('Color', 'w', 'Units', 'inches', ...
    'Position', [1, 1, 11.5, 8.2]);
ax = axes(fig, 'Position', [0.18, 0.16, 0.76, 0.69]);
ax.Toolbar.Visible = 'off';
hold(ax, 'on');
dashedColor = [0.55, 0.55, 0.55];

if pathway == "L6"
    transitionBeta = 0.175;
    solidMask = one.beta <= transitionBeta;
    dashedMask = one.beta >= transitionBeta;
    plot(ax, one.beta(solidMask), one.trueMaxRealLambda(solidMask), '-', ...
        'Color', movedColor, 'LineWidth', 3.5, ...
        'DisplayName', 'Real tuning, moved fixed point');
    plot(ax, one.beta(dashedMask), one.trueMaxRealLambda(dashedMask), '--', ...
        'Color', dashedColor, 'LineWidth', 3.5, ...
        'HandleVisibility', 'off');
else
    transitionBeta = -0.075;
    dashedMask = one.beta <= transitionBeta;
    solidMask = one.beta >= transitionBeta;
    plot(ax, one.beta(dashedMask), one.trueMaxRealLambda(dashedMask), '--', ...
        'Color', dashedColor, 'LineWidth', 3.5, ...
        'HandleVisibility', 'off');
    plot(ax, one.beta(solidMask), one.trueMaxRealLambda(solidMask), '-', ...
        'Color', movedColor, 'LineWidth', 3.5, ...
        'DisplayName', 'Real tuning, moved fixed point');
end
plot(ax, one.beta, one.fppMaxRealLambda, '-', ...
    'Color', fppColor, 'LineWidth', 3.2, ...
    'DisplayName', 'FPP, matched w = -\beta');
zeroIndex = find(abs(one.beta) < 1e-12, 1);
plot(ax, one.beta(zeroIndex), one.trueMaxRealLambda(zeroIndex), 'o', ...
    'Color', movedColor, 'MarkerSize', 9, ...
    'MarkerFaceColor', movedColor, 'HandleVisibility', 'off');
plot(ax, one.beta(zeroIndex), one.fppMaxRealLambda(zeroIndex), 's', ...
    'Color', fppColor, 'MarkerSize', 9, ...
    'MarkerFaceColor', fppColor, 'HandleVisibility', 'off');
yline(ax, 1, ':', 'Color', [0.28, 0.28, 0.28], ...
    'LineWidth', 2.2, 'DisplayName', 'Stability boundary');

xlabel(ax, '\beta (fractional whole-pathway change)', ...
    'Interpreter', 'tex', 'FontSize', 28);
ylabel(ax, 'Max Real Eigenvalue', 'FontSize', 28);
title(ax, panelTitle, 'FontSize', 29, 'FontWeight', 'normal');

set(ax, 'FontName', 'Arial', 'FontSize', 26, 'LineWidth', 1.4, ...
    'Box', 'on', 'TickDir', 'out', 'XLim', [-0.5, 0.5]);
ax.GridAlpha = 0.15;
grid(ax, 'on');

lgd = legend(ax, 'Location', legendLocation, 'FontName', 'Arial', ...
    'FontSize', 18, 'Box', 'on', 'Interpreter', 'tex');
lgd.ItemTokenSize = [25, 15];

savefig(fig, outputFig);
exportgraphics(fig, outputPdf, 'ContentType', 'vector', ...
    'BackgroundColor', 'white');
close(fig);
fprintf('Saved %s\n', outputPdf);
end
